project:
  type: book

book:
  title: "Enrightening Mathematics Revision Book Volume"
  author: "Martin Nyamu and Ken Gatungo"
  date: "10/01/2023"
  search: true
  repo-url: https://github.com/analystnyamu/Math_Book/
  repo-actions: [edit]
  downloads: [epub,pdf]
  sharing: [twitter, facebook]
  
  chapters:
    - index.qmd
    - intro.qmd
    - Natural Numbers.qmd
    - Factors.qmd
    - Divisibility Test.qmd
    - GCD and LCM.qmd
    - Integers.qmd
    - Fractions.qmd
    - Decimals Sqr & Sqrt.qmd
    - Algebraic Expression.qmd
    - Rate Ratio, Proportion and Percentage.qmd
    - Length Area Volume and Capacity.qmd
    - Mass Weight and Density.qmd
    - Time.qmd
    - Linear Equations.qmd
    - Commercial Arithmetic.qmd
    - Co-Ordinates and Graphs.qmd
    - Angles and Plane Figures.qmd
    - Geometrical Constructions.qmd
    - Scale Drawing.qmd
    - Model Sample Papers.qmd
    - Answers to Problems to Solve.qmd
    - Answers to Model Sample Papers.qmd
    
    
comments:
  hypothesis: true
  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

