project:
  type: book
  output-dir: _book

book:
  title: "Enlightening Mathematics Revision Book Volume 1"
  author: "Martin Nyamu and Ken Gatungo"
  date: "08 Nov 2018"
  
copyright: "© 2024 Martin Wanjiru and Kenneth Gatungo. All rights reserved."

  page-footer:
    left: |
      Enlightening Mathematics Revision Book Volume 1 (2e) was written by Martin Nyamu and Ken Gatungo.

  search: true
  repo-url: https://github.com/analystnyamu/EnlighteningMath/
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [epub,pdf]  # Removed pdf from downloads
  sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - intro.qmd
    - Natural Numbers.qmd
    - Factors.qmd
    - Divisibility Test.qmd
    - GCD and LCM.qmd
    - Integers.qmd
    - Fractions.qmd
    - Decimals Sqr & Sqrt.qmd
    - Algebraic Expression.qmd
    - Rate Ratio, Proportion and Percentage.qmd
    - Length Area Volume and Capacity.qmd
    - Mass Weight and Density.qmd
    - Time.qmd
    - Linear Equations.qmd
    - Commercial Arithmetic.qmd
    - Coordinates_and_Graphs.qmd
    - Angles and Plane Figures.qmd
    - Geometrical Constructions.qmd
    - Scale Drawing.qmd
    - Model Sample Papers.qmd
    - Answers to Problems to Solve.qmd
    - Answers to Model Sample Papers.qmd

metadata:
  crossref:
    chapters: true
  documentclass: scrbook
  documentclassoptions: [openany]
  comments:
    hypothesis: true
  # Math and header includes remain unchanged

format:
  html:
    theme:
      - cosmo
      - EM.scss
    code-link: true
    toc: true
    number-sections: true
    colorlinks: true
    author-meta: "Martin Nyamu & Kenneth Gatungo"
    # Avoiding a single-page format
    paginate: true                   # Ensure pagination is enabled
    toc-depth: 2  # Define the depth of sections in the TOC
    number-chapters: true
    next-chapter: true              # Include next chapter navigation
    previous-chapter: true          # Include previous chapter navigation
    cover-image: "images/cover.png"
    
  pdf:
    pdf-engine: xelatex
    includes:
      in-header: header.tex  # This is a custom LaTeX file for additional formatting
      text: |
        \usepackage{libertinus}     # Use Libertinus font for text and math
        \usepackage{libertinust1math} # Libertinus math font package
    header-includes:
      - \let\cleardoublepage\clearpage
      - \usepackage{cancel}  # Include the cancel package
      - \sloppy
      - \usepackage{caption}
      - \captionsetup{justification=centering, margin=1cm}
      - \usepackage{scrhack}
      - \usepackage{etoolbox}  # Package for modifying existing commands
      - \usepackage{etoolbox}
      - \makeatletter
      - \patchcmd{\chapter}{\clearpage}{}{}{}
      - \patchcmd{\section}{\clearpage}{}{}{}
      - \makeatother
      - \setlength{\parskip}{0pt}  % Set paragraph spacing to zero
      - \usepackage{setspace}
      - \setstretch{1.0}  % Adjust line spacing (1.0 is single spacing, 1.5 for 1.5 spacing, etc.)
      - \usepackage[margin=1in]{geometry}  % Adjusts the page margins (1 inch in this example)
      -  \usepackage[skip=0pt]{caption}  % Reduces space before figure captions
    fontsize: 12pt
    colorlinks: true
    fig_caption: true  # Ensure figure captions are enabled
    keep_tex: true     # Keep the .tex file for debugging
    geometry: a4paper, margin=1in  # Set the paper size to A4
    toc: true  # Enable table of contents
    number-sections: true  # Enable section numbering
    cover-image: "images/cover.png"  # Path to your cover image

# Options for code execution remain unchanged
execute:
  echo: false
  warning: false
  error: false
  eval: true
  include: true
