metadata:
  crossref:
    chapters: true
  documentclass: scrbook
  geometry: a4paper
  block-headings: true
  comments:
    hypothesis: true
  math:
    mathjax:
      url: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js'
      config: TeX-AMS_HTML
      extensions:
        - cancel
  header-includes:
    - \let\cleardoublepage\clearpage
    - \usepackage{cancel}  # Include the cancel package
  geometry: margin=1in
  cover-image: images/cover.png
  colorlinks: true
  bibliography:
    - references.bib
  title: "Enlightening Mathematics Revision Book Volume 1"
  author: "Martin Nyamu and Ken Gatungo"
  date: "10/01/2023"

project:
  type: book
  output-dir: _book

book:
  title: "Enlightening Mathematics Revision Book Volume 1"
  author: "Martin Nyamu and Ken Gatungo"
  date: "10/01/2023"
  cover-image: "images/cover.png"  # Path to your cover image

  page-footer:
    left: |
      Enlightening Mathematics Revision Book Volume 1 (2e) was written by Martin Nyamu and Ken Gatungo.

  search: true
  repo-url: https://github.com/analystnyamu/EnlighteningMath/
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [epub, pdf]
  sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - intro.qmd
    - Natural Numbers.qmd
    - Factors.qmd
    - Divisibility Test.qmd
    - GCD and LCM.qmd
    - Integers.qmd
    - Fractions.qmd
    - Decimals Sqr & Sqrt.qmd
    - Algebraic Expression.qmd
    - Rate Ratio, Proportion and Percentage.qmd
    - Length Area Volume and Capacity.qmd
    - Mass Weight and Density.qmd
    - Time.qmd
    - Linear Equations.qmd
    - Commercial Arithmetic.qmd
    - Co-Ordinates and Graphs.qmd
    - Angles and Plane Figures.qmd
    - Geometrical Constructions.qmd
    - Scale Drawing.qmd
    - Model Sample Papers.qmd
    - Answers to Problems to Solve.qmd
    - Answers to Model Sample Papers.qmd

comments:
  hypothesis: true

format:
  pdf:
    toc: true                        # Enable table of contents for PDF
    number-sections: true            # Enable section numbering
    cover-image: "images/cover.png"  # Path to cover image for PDF
    colorlinks: true                 # Enable colored links in PDF

  epub:
    cover: cover.qmd                # Path to cover image for EPUB
    toc: true                        # Enable table of contents for EPUB

# Options for code execution
execute:
  echo: true                       # Display code in the output
  warning: false                   # Suppress warnings in the output
  error: false                     # Suppress errors in the output
  eval: true     # Execute the R code
  include: true   # Include both code and output in the final document

# Pandoc-specific options
pandoc:
  to: latex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: pdflatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
