
  project:
    type: book
    output-dir: _book

  book:
    title: "Enlightening Mathematics Revision Book Volume 1"
    #reader-mode: true
    
    
    page-footer:
      left: |
        Enlightening Mathematics Revision Book Volume (2e) was written by Martin Nyamu and Ken Gatungo.
      right: |
       This book was built with <a href="https://quarto.org/">Quarto</a>.
       
    author: "Martin Nyamu and Ken Gatungo"
    date: "10/01/2023"
    search: true
    repo-url: https://github.com/analystnyamu/EnlighteningMath/
    repo-branch: main
    repo-actions: [edit, issue]
    downloads: [epub,pdf]
    sharing: [twitter, facebook]
  
    chapters:
      - index.qmd
      - intro.qmd
      - Natural Numbers.qmd
      - Factors.qmd
      - Divisibility Test.qmd
      - GCD and LCM.qmd
      - Integers.qmd
      - Fractions.qmd
      - Decimals Sqr & Sqrt.qmd
      - Algebraic Expression.qmd
      - Rate Ratio, Proportion and Percentage.qmd
      - Length Area Volume and Capacity.qmd
      - Mass Weight and Density.qmd
      - Time.qmd
      - Linear Equations.qmd
      - Commercial Arithmetic.qmd
      - Co-Ordinates and Graphs.qmd
      - Angles and Plane Figures.qmd
      - Geometrical Constructions.qmd
      - Scale Drawing.qmd
      - Model Sample Papers.qmd
      - Answers to Problems to Solve.qmd
      - Answers to Model Sample Papers.qmd
    
    
  comments:
    hypothesis: true
  
  format:
    pdf:
      documentclass: scrbook
      papersize: a4paper
      toc: true
      number-sections: true
      geometry: "left=1in, right=1in, top=1in, bottom=1in"  # Margins for PDF
      colorlinks: true
    html:
      toc-depth: 2              # Depth of table of contents in HTML
      theme: cosmo              # Use the 'cosmo' theme for HTML
      css: styles.css           # Optional custom CSS for styling
      code-link: true
    epub:
      toc: true                 # Table of contents in EPUB


  # Options for code execution
  execute:
    echo: true         # Show R code in output
    warning: false     # Suppress warnings
    error: false       # Suppress errors

