---
header-includes:
  - \usepackage{amsmath}  # Example package
  - \usepackage{cancel}
  - \usepackage{graphicx}  # Example package for graphics
---

# Chapter 11: Mass, Weight and Density {.unnumbered}

## Mass, Weight and Density {.unnumbered}

**Mass**, is the quantity of matter in an object? The Mass of an object
is constant everywhere. Its SI unit is Kilogram (K.g).

**Weight**, is the pull of the earth on an object. The weight of an
object varies from one place to another on the earth's surface. Its SI
unit is Newton (N). It is given by mass multiplied by the gravitational
force (g).

$Weight (N) = mass (kg) \times gravity (N/kg).$

**Density**, is mass per unit volume. Its SI unit is Kilogram per Cubic
meter ($kgm^-3$)

$$Density= \frac{mass}{volume}$$
$$Density \,of\, mixture=\frac{mass \,of\, mixture}{volume\, of \,mixture} $$

::: {.callout-note collapse="false"}
## Conversion of Units

```{=latex}
\begin{equation}
\begin{split}
1 \,tonne &= 1,000\, Kilograms\\
1 \,kilogram &= 1,000 \,grams\\
1g/cm^3& = 1,000 Kg/m^3
\end{split}
\end{equation}
```
:::

## Solved Examples

::: {.callout-note collapse="false"}
## Example 1

2.5 litres of water of density $1g/cm^3$ is added to 4 litres of alcohol
of density $0.8 g/cm^3$. Calculate in 3 significant figures, the density
of the mixture in its SI unit.  (3mks)
:::

::: {.callout-caution collapse="true"}
## Solution

$$Density \,of \,Mixture (D.M)=\frac{Mass\, of\,mixture}{Volume\, of \,mixture}$$
$$
\begin{aligned}
\text{Volume of water} &= 2,500 \, \text{cm}^3 \\
\text{Mass of water} &= 2,500 \, \text{cm}^3 \times 1 \, \text{g/cm}^3 \\
&= 2,500 \, \text{g} \\
\text{Volume of alcohol} &= 4,000 \, \text{cm}^3 \\
\text{Mass of alcohol} &= 4,000 \, \text{cm}^3 \times 0.8 \, \text{g/cm}^3 \\
&= 3,200 \, \text{g}
\end{aligned}
$$

$$
\begin{aligned}
\text{Mass of Mixture} &= 2,500 \, \text{g} + 3,200 \, \text{g} \\
&= 5,700 \, \text{g} \\
\text{Volume of mixture} &= 2,500 \, \text{cm}^3 + 4,000 \, \text{cm}^3 \\
&= 6,500 \, \text{cm}^3 \\
\therefore \text{Density (D.M.)} &= \frac{5,700}{6,500} \, \text{g/cm}^3 \\
&= 0.8769 \, \text{g/cm}^3 \\
&= 877 \, \text{Kg/m}^3
\end{aligned}
$$
:::

::: {.callout-note collapse="false"}
## Example 2

wo coils of the same mass are made by winding zinc of different gauges
and lengths. The first coil is made by winding 648 m of wire with a
cross-sectional diameter of 5.4mm and the second coil is made by winding
450 m with different cross-sections. Find the cross-sectional radius of
the second coil. $(3mks)$
:::

::: {.callout-caution collapse="true"}
## Solution

**Note:** Since mass is proportional to volume for the same density, the
volume of the first coil is equal to volume of the second coil.

$$
\begin{aligned}
\textbf{First coil volume:} \\
\frac{22}{7} \times \left(\frac{5.4}{2}\right)^2 \times 648,000 &= 14,846,605.71 \, \text{mm}^3 \\
\\
\textbf{Second coil volume:} \\
\frac{22}{7} \times r^2 \times 450,000 &= 1,414,285.714r^2 \, \text{mm}^3 \\
\\
\textbf{Equating second coil volume to first coil volume:} \\
1,414,285.714r^2 &= 14,846,605.71 \, \text{mm}^3 \\
\\
\frac{\cancel{1,414,285.714}r^2}{\cancel{1,414,285.714}} &= \frac{\cancelto{10.4976}{14,846,605.71}}{\cancel{1,414,285.714}} \\
r^2 &= 10.4976 \, \text{mm}^2 \\
\\
\therefore \, r &= 3.24 \, \text{mm}
\end{aligned}
$$
:::

::: {.callout-note collapse="false"}
## Example 3

The external measurements of a closed metal box are 1.6 m long, 0.7 m
wide, and 0.4 m high. The metal used in making box is 1.0 cm thick and
has a density of 0.85 g/cm3. If the box contains 40 packets of 12
similar tools each and each tool has a mass of 115 g, calculate:

a\) The volume of metal used in making the box. $(4mks)$

b\) The mass of the empty box in Kilograms to 3 significant figures.
$(3mks)$

c\) The total mass of the box in kilograms to 3 significant figures.
$(3mks)$
:::

::: {.callout-caution collapse="true"}
## Solution

a\) 

```{=latex}
$$
\begin{aligned}
\textbf{Volume of the Cuboid (v):} & \\
v &= \text{Length} \times \text{Width} \times \text{Height} \\
\textbf{External Measurement:} & \\
\text{Length} &= 160 \, \text{cm} \\
\text{Width} &= 70 \, \text{cm} \\
\text{Height} &= 40 \, \text{cm} \\
\textbf{Internal Measurement:} & \\
\text{Thickness} &= 1 \, \text{cm} \\
\text{Internal Length} &= 158 \, \text{cm} \\
\text{Internal Width} &= 68 \, \text{cm} \\
\text{Internal Height} &= 38 \, \text{cm} \\ 
\end{aligned}
$$
```

```{=latex}
\[
\begin{aligned}
\text{Width} &= 68 \, \text{cm} \\
\text{Height} &= 38 \, \text{cm} \\ 
\textbf{External Volume:} \\
160 \times 70 \times 40 &= 448,000 \, \text{cm}^3 \\ 
\textbf{Internal Volume:} \\
158 \times 68 \times 38 &= 408,272 \, \text{cm}^3 \\ 
448,000 \, \text{cm}^3 - 408,272 \, \text{cm}^3 &= 39,728 \, \text{cm}^3 \\ 
\therefore \textbf{Volume of the metal} &= 39,728 \, \text{cm}^3 
\end{aligned}
\]
```

b\) 

```{=latex}
\[
\begin{aligned}
\text{Mass} &= \text{density} \times \text{volume} \\
&= 0.85 \, \text{g/cm}^3 \times 39,728 \, \text{cm}^3 \\ 
&= 33,768.8 \, \text{g} \\ 
\frac{33,768.8}{1000} &= 33.7688 \, \text{Kg} \\ 
\therefore \textbf{Mass of the empty box} &= 33.8 \, \text{Kg}
\end{aligned}
\]
```

c\) 

```{=latex}
\[
\begin{aligned}
\textbf{Mass of tools:} \\
12 \times 40 \times 115 &= 55,200 \, \text{g} \\
\frac{55,200}{1000} &= 55.2 \, \text{Kg} \\
\therefore \textbf{The total Mass} &= 55.2 + 33.8 \\
&= 89.0 \, \text{Kg}
\end{aligned}
\]
```
:::

::: {.callout-note collapse="false"}
## Problems to Solve

1.  A solid block in the shape of a cylinder has a height of 14cm and
    weighs 26kg. If it is made of material of density $0.45g/cm^3$, find
    the radius of the cylinder to four significant figures. Take
    $\pi=\frac{22}{7}$    $(3mks)$

2.  $2000\, \text{cm}^3$ of a mixture consists of 2.5 kg of substance x and 7.5
    kg of substance y. find the density of mixture in $g/cm^3$
     $(3mks)$

3.  An artisan has 63kg of metal of density $7g/cm^3$. He intends to use
    it to make a rectangular pipe with external dimensions 12cm by 15cm
    and internal dimensions 10cm by 12 cm. Calculate the length of the
    pipe in metres.  $(3mks)$

4.  A solid metal cuboid 2.1m long, 0.8m wide, and 0.75m high of
    material of density $0.75g/cm^3$. Calculate its mass in kilograms.
     $(2mks)$

5.  A metal R is an alloy of two metals X and Y. Metal X has a mass of
    70g and a density of $16000kg/m^3$. Metal Y has a mass of 42g and a
    density of $4000 kg/m^3$. In 4 significant figures, calculate the
    density of the metal R in its SI unit.  $(4mks)$

6.  Two coils of the same mass are made by winding aluminum wire of
    different gauges and lengths. If the first coil is made by winding
    540 m of the wire with diameter 1.96 mm cross-sectional diameter and
    the second coil is made by winding a certain length of the wire with
    a cross-sectional diameter of 2.94 mm, find the length of the second
    coil wire.  $(3mks)$

7.  The external measurements of a wooden box are 1.2 m long, 65 cm
    wide, and 40 cm high. The wood used in making the box is 2 cm thick
    and has a density of $950 Kg/m^3$. Given that the box contains 30
    packets of tools and each packet holds a dozen tools each weighing
    125 g, calculate:

    a\) The volume of wood used in making the box.  $(4mks)$

    b\) The mass of the empty box in kilograms to four significant
    figures. $(3mks)$

    c\) The total mass of the box in kilograms to 3 significant figures.
    $(3mks)$
:::
