[build]
  command = "curl -sSL https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb -o quarto.deb && \
             sudo dpkg -i quarto.deb && \
             quarto render"
  publish = "_book"

