<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martin Nyamu &amp; Kenneth Gatungo">

<title>SECTION TWO – Enlightening Mathematics Revision Book Volume 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Answers to Problems to Solve.html" rel="next">
<link href="./Scale Drawing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Model Sample Papers.html">SECTION TWO</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Enlightening Mathematics Revision Book Volume 1</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/analystnyamu/EnlighteningMath/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Enlightening-Mathematics-Revision-Book-Volume-1.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Enlightening-Mathematics-Revision-Book-Volume-1.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Natural Numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1: Natural Numbers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2: Factors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Divisibility Test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Three: Divisibility Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./GCD and LCM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4: G.C.D and L.C.M</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Integers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5: Integers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Fractions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 6: Fractions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Decimals Sqr &amp; Sqrt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Seven: Decimals, Squares, and Square Roots</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Algebraic Expression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Eight: Algebraic Expressions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rate Ratio, Proportion and Percentage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Nine: Rate, Ratio, Proportion, and Percentage</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Length Area Volume and Capacity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Ten: Length, Area, Volume, and Capacity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mass Weight and Density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Eleven: Mass, Weight and Density</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Time.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Twelve: Time</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear Equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 15: Linear Equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Commercial Arithmetic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Fourteen: Commercial Arithmetic</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Coordinates_and_Graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Fifteen: Co-Ordinates and Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Angles and Plane Figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Sixteen: Angles and Plane Figures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Geometrical Constructions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Seventeen: Geometrical Constructions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Scale Drawing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter Eighteen: Scale Drawing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Model Sample Papers.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">SECTION TWO</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Answers to Problems to Solve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SECTION THREE</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Answers to Model Sample Papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SECTION FOUR</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#model-samples-papers" id="toc-model-samples-papers" class="nav-link active" data-scroll-target="#model-samples-papers">Model Samples Papers</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/analystnyamu/EnlighteningMath/edit/main/Model Sample Papers.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/analystnyamu/EnlighteningMath/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SECTION TWO</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="model-samples-papers" class="level2">
<h2 class="anchored" data-anchor-id="model-samples-papers">Model Samples Papers</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate without using tables or calculators. <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[ \frac{\frac{3}{7}\,of\,28\div80\times-\frac{40}{3}}{-2\times5+(14\div7)\times3}\]</span></p>
<ol start="2" type="1">
<li><p>Felix has four times as many ducks as hens and three-quarters as many turkeys as ducks.</p>
<p>a) If he has x hens, write down a simplified expression in x for the total number of birds <span class="math inline">\((2mks)\)</span></p>
<p>b) Find the total number of birds given that the Felix has 45 turkeys.<span class="math inline">\((2mks)\)</span></p></li>
<li><p>Given that <span class="math inline">\(x=4,\, y= -2,\, and \,z= -3\)</span> evaluate. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[ \frac{2(x+z)^2-(x-y)(y-z)}{4(x+y)-2(y-z)}\]</span></p>
<ol start="4" type="1">
<li><p>Using a ruler and a pair of compasses only, construct triangle PQR in which <span class="math inline">\(PQ = 5.2cm\)</span> <span class="math inline">\(QR=7.5cm\)</span> and Angle <span class="math inline">\(PQR = 45^0\)</span>. By construction bisect angle PQR to meet line PR at a point M. find the ratio <span class="math inline">\(PM:MR\)</span>.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Use square and square root table to evaluate to 4 significant figures, the expression. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\sqrt[]{24.640-(4.362)^2} \]</span></p>
<ol start="6" type="1">
<li><p>The cost of a TV outside is US$ 1200. Kelvin decides to buy one TV through an agent who deals with Japanese Yen. The agent charges him a commission of 5% on the price of the TV and further 2,000 Yen as important tax. To the nearest Ksh. how much will he need to send to the agent to obtain the TV, given that:- <span class="math inline">\((3mks)\)</span></p>
<p><span class="math inline">\(1\,US\, \$ = 110.95 \,Yen\)</span></p>
<p><span class="math inline">\(1\,US \$ = Kshs. \,102.80\)</span></p></li>
<li><p>A two –digit number is such that the sum of the ones digit and the tens digit is 4. If the digits are reversed, the number formed exceeds the original number by 18. Find the number. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Metal block of side 5.6 cm was melted and the molten material used to make a sphere. In three significant figures, find the radius of the sphere in metres (take <span class="math inline">\(\pi =\frac{22}{7}\)</span>) <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Solve the simultaneous equations <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<ol start="10" type="1">
<li><p>Kinyua bought soya and millet at Ksh. 70 per kg and Ksh. 40 per kg respectively. He then mixed them and sold the mixture at Ksh. 60 per kg making a profit of 20%. Determine the ratio of soya to millet in mixture. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>An aircraft left Nairobi at 2245h on Monday and arrived in Cape Town on Tuesday at 0300h. It departed from Cape Town at 0330h and arrived in Washington DC at 0630h on Wednesday. Find the travel ling time for the whole journey from Nairobi to Washington DC took? <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A town B is 250 km due east of town A. Another town C is 200 km on a compass bearing of <span class="math inline">\(S40^0E\)</span> from town B. use scale drawing to find the distance and bearing of town C from A. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>1.784 kg of sugar whose density is <span class="math inline">\(1.08g/cm^3\)</span> and 0.744kg of salt whose density is <span class="math inline">\(1.04g/cm^3\)</span> are mixed together for a certain experiment. What is the density of the mixture in <span class="math inline">\(kg/m^3\)</span>? ( Give the answer to 4. s.f) <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The interior angle of a regular polygon is 5 times the exterior angle. How many sides does the polygon have? <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Find the least number of steps in staircase if, when I go up 3 steps at a time, 4 steps at a time or 6 steps at a time, there is always 1 step remaining at the top. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>An arc of a circle of length 37.4cm subtends an angle of <span class="math inline">\(153^0\)</span> at the centre of the circle. Calculate the area of the sector bounded by this arc. Take <span class="math inline">\(\pi=\frac{22}{7}\)</span>. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>Kirote and Kanze bought a bus which could carry 50 passengers when full. The bus uses Nairobi-Machakos route and charges Ksh. 160 per passengers for one way. The bus makes three trips between the two towns daily. The cost of fuel was Ksh. 2500 per day. The driver and the conductor are paid allowances of Ksh. 1500 and Ksh. 800 respectively. A further of Ksh. 5,000 per day are set aside for maintenance.</p>
<p>a) One day the bus was full on every trip.</p>
<ol type="i">
<li><p>How much money was collected from the passengers that day? <span class="math inline">\((2mks)\)</span></p></li>
<li><p>How much was the net profit. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p>b) On another day, the minibus was 80% full on average for the trips how much did Kanze get if the days profit was shared to the ratio 2:3? <span class="math inline">\((5mks)\)</span></p></li>
<li><p>The following measurement were recorded in a field book of a farm using <span class="math inline">\(XY\)</span> as the base line <span class="math inline">\(XY = 450\,m\)</span></p>
<p><img src="images/MP1_Q18.png" class="img-fluid"></p>
<p>a) Using a scale, draw an accurate map of the farm. <span class="math inline">\((3mks)\)</span></p>
<p>b) Determine the actual area of the farm in hectares. <span class="math inline">\((4mks)\)</span></p>
<p>c) If the farm is on sale at Ksh. 280,000 per hectare, find how much the farm costs.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Four ships are at sea such that a steam-liner W is 250 km on a bearing of <span class="math inline">\(030^0\)</span> from a cargo ship Q. A trawler M is 350 km on a bearing of <span class="math inline">\(145^0\)</span> from the cargo ship Q and a yacht R is due west of Q and on a compass bearing of <span class="math inline">\(N60^0W\)</span> from M</p>
<p>a) Using a scale of 1 cm=50 km, draw an accurate scale drawing showing the positions of W, Q, M, and R. <span class="math inline">\((5mks)\)</span></p>
<p>b) By measurement from your scale drawing determine:</p>
<p>i) The distance and bearing of R from W. <span class="math inline">\((3mks)\)</span></p>
<p>ii) The distance WM. <span class="math inline">\((1mk)\)</span></p>
<p>iii) The distance RM. <span class="math inline">\((1mk)\)</span></p></li>
<li><p>An electronics manufacturer makes speakers and sells them to a distributor at a profit of <span class="math inline">\(20\%\)</span>. The distributor sells the speakers to a retailer at a profit of <span class="math inline">\(25\%\)</span>. The retailer finally sells the speakers to customers at a profit of <span class="math inline">\(40\%\)</span>.</p>
<p>a) A customer paid Ksh. 1,680 for a portable speaker. Find how much it had cost the manufacturer to make the speaker. <span class="math inline">\((3mks)\)</span></p>
<p>b) A retailer bought a speaker which had cost the manufacturer Ksh. 5,600 to make. Calculate the amount he paid for it. <span class="math inline">\((3mks)\)</span></p>
<p>c) A customer bought a pioneer speaker at Ksh. 6,300. Calculate the much the distributor had paid for the same radio. <span class="math inline">\((2mks)\)</span></p>
<p>d) Express as a percentage the amount the customer paid for the speaker in (c) above to the amount the distributor paid for it. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Four trucks A, B, C, and D are used to transport 42,000 bags of maize to a depot. However, trucks A and B together take 40 days to transport the same number of bags while trucks C and D together take 25 days. Truck A carries <span class="math inline">\(1\frac{1}{2}\)</span> times the number of bags B carries and C carries <span class="math inline">\(1\frac{4}{5}\)</span> times as much as D.</p>
<p>a) Determine the number of bags of maize transported by each truck per day.<span class="math inline">\((5mks)\)</span></p>
<p>b) All the trucks A, B, C, and D work together for 5 days, after which truck C and D are withdrawn. A and B work together for another 5 days after which truck A breaks down. How long does truck B take to complete the rest of the remaining bags? <span class="math inline">\((5mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Use the tables of squares and square roots only to find the value of; <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[ \left(0.0847\right)^\frac{1}{2}+\left(2.35\right)^2\]</span></p>
<ol start="2" type="1">
<li>Without using calculator, evaluate.<span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{2\frac{4}{5}+3\frac{1}{5}\div\frac{7}{8}\,of\,4\frac{4}{7}-\frac{3}{5}}{1\frac{3}{4}\div3\frac{1}{2}-\frac{5}{12}+\frac{2}{3}} \]</span></p>
<ol start="3" type="1">
<li><p>Two years ago, Musa was three times as old as Ahmed. In four years’ time, Musa will be twice as old as Ahmed. Find their present ages <span class="math inline">\((4mks)\)</span></p></li>
<li><p>On a map with a scale of 1:16,000, a banana plantation covers an area of <span class="math inline">\(70cm^2\)</span>. Find the area of the plantation in hectares. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Canadian tourist came to Kenya with sterling pounds 4500 which he exchanged to Kenyan shillings. He spent a quarter of the money and exchanged the rest to sterling pounds on leaving. How much in sterling pounds did he receive? <span class="math inline">\((4mks)\)</span></p>
<p>Exchange rate in Ksh. per pound</p></li>
</ol>
<pre><code>           Buying          Selling
           119.74          119.88
              </code></pre>
<ol start="6" type="1">
<li><p>The sums of interior angles of two regular polygons of sides’ n-1 and n are in the ratio 3:4. Calculate;</p>
<p>a) The value of n.&nbsp;<span class="math inline">\((2mks)\)</span></p>
<p>b) The size of interior angle of each polygon. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>John bought six exercise books and three text books for Ksh. 660. If he had bought three similar exercise books and six text books, he would have paid Ksh. 210 more. How much would he pay for five exercise books and five text books? <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Find the least number of biscuits that can be packed into carton boxes which contain either 4 or 9 or 24 or 40 with none left over.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>In order to complete a certain job in 10 days, a company employs 30 workers to work at the rate of 8 hours a day. Determine how long it would take 20 workers working at the rate of 12 hours a day to complete the same job. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Simplify the expression. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\frac{y^2-4x-4xy+y}{(y+1)(4x^2-xy)}\]</span></p>
<ol start="11" type="1">
<li><p>A two digit number is such that the sum of the ones and the tens digit is 11. If the Digits are reversed; the original number exceeds the new number formed by 9. Find the number. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Joyce on her cycling practice cycled on a bearing of <span class="math inline">\(125^0\)</span> for 5.5km, then on a bearing of <span class="math inline">\(180^0\)</span> for 6.7km finally he turned northwards for 12.5km, by scale drawing determine the distance and compass bearing of her final position from the starting point. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Njoki bought Mike a suit for Ksh. 3600. This price was such that the shopkeeper had allowed a discount of 10% on the marked price in order to make a profit of 20%. Calculate both the marked price and the buying price of the suit. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Bronze is made by mixing tin, brass, and zinc in the ratio 3:5:4. A piece of bronze contains 7.2 kg of tin. Determine the total mass of brass and zinc in that piece of steel. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>A cylindrical solid of length 40cm and radius 7cm is melted to form 10 similar spherical solids. Determine the radius of each spherical solid. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Starting from midnight the minute hand of a clock moved so that the clock is showing 24 minutes past midnight.</p>
<p>a) Find the angle through which the minute hand has moved. <span class="math inline">\((1mk)\)</span></p>
<p>b) Given that the minute hand is 14 cm long, calculate the length of the arc it describes in that time. <span class="math inline">\((2mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>Simon sold an article at Ksh. 5,100 after allowing his customer a 15% discount on the marked price of the article. In so doing he made a profit of 25%.</p>
<p>a) Calculate:</p>
<p>i) The marked price of the article. <span class="math inline">\((2mks)\)</span></p>
<p>ii) The price at which Simon had bought the article <span class="math inline">\((2mks)\)</span></p>
<p>b) If Simon had sold the same article without giving a discount. Calculate the percentage profit he would have made to three significant figures. <span class="math inline">\((3mks)\)</span></p>
<p>c) To clear his stock, Simon decided to sell the remaining articles at a loss of 20%.Calculate the price at which he sold each article. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>(a) Using a ruler and a pair of compasses only construct triangle ABC in which <span class="math inline">\(BC = 8cm\)</span>, <span class="math inline">\(AB = 6cm\)</span> angle <span class="math inline">\(ABC = 67.5^0\)</span> <span class="math inline">\((4mks)\)</span></p>
<p>(b) Measure AC and angle ACB <span class="math inline">\((2mks)\)</span></p>
<p>(c) Construct a circle that passes through AB, AC and BC <span class="math inline">\((3mks)\)</span></p>
<p>(d) What is the radius of this circle? <span class="math inline">\((1mk)\)</span></p></li>
<li><p>A bus had 48 passengers at the begining of the journey, 20 passengers alighted at the first stop while 12 boarded. 8 of those who boarded at the first stop alighted at the second stop and 16 got in. The bus did not stop again upto the final destination. The charges from the starting point were Ksh. 100 upto the first stop, Ksh. 150 upto the second stop, and Ksh. 220 upto the final destination.</p>
<p>a) How many passengers alighted at the final destination? <span class="math inline">\((3mks)\)</span></p>
<p>b) How many passengers were ferried by the bus through the journey? <span class="math inline">\((2mks)\)</span></p>
<p>c) How much money was collected during the trip? <span class="math inline">\((5mks)\)</span></p></li>
<li><p>(a) The angle of elevation of the top of a tree from a point P on the horizontal ground <span class="math inline">\(28.5^0\)</span>. From another point Q, five meters from P towards the base of the tree, the angle of elevation of the top of the tree is <span class="math inline">\(37.2^0\)</span>. By scale drawing calculate to one decimal place the height of the tree.<span class="math inline">\((4mks)\)</span></p>
<p>(b) Four points A, B, C and D lie on the same plane. Point A is due southwest of point B. Point C is 70 Km on a bearing of <span class="math inline">\(S60^0E\)</span> from B. Point D is equidistant from B, Q and C.</p>
<p>i) Using the Scale: 1 cm represents 10km, construct a diagram showing the position of B, C, Q and D. <span class="math inline">\((4mks)\)</span></p>
<p>ii) Determine the distance between A and B <span class="math inline">\((1mk)\)</span></p>
<p>iii) Determine the bearing of D from B. <span class="math inline">\((1mk)\)</span></p></li>
<li><p>Water flows through a cylindrical pipe of diameter 2.8 cm at a speed of 70m/min.</p>
<p>a) Calculate the volume of the water delivered by the pipe per minute in litres.<span class="math inline">\((3mks)\)</span></p>
<p>b) A cylindrical storage tank of depth 5m is filled by water from this pipe and at the same rate of flow. Water begins flowing into the empty storage tank at 9.30 p.m. and is full by 2.10 a.m. Calculate the area of the cross-section of this tank in <span class="math inline">\(m^2\)</span>. <span class="math inline">\((4mks)\)</span></p>
<p>c) A family consumes the capacity of this tank in one month. The cost of water is Ksh. 25 per thousand litres plus a fixed basic charge of Ksh. 1800.60. Calculate the cost of this family’s water bill for the month. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Without using a calculator or mathematical tables, evaluate: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{15-6\times-14-21\div-3}{9\times3+-8(5-(-2))} \]</span></p>
<ol start="2" type="1">
<li><p>Hannah finds that she needs 29 beacons placed 42 m apart when she surveys a length of road. If she was to place the beacons 49 m apart,</p>
<p>a) How many beacons would she need? <span class="math inline">\((2mks)\)</span></p>
<p>b) What is the shortest distance that can be divided into exact portions of 25, 30 or 40 metres giving a remainder of 3 metres. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Two friends Wakuraya and Muchoki have goats. Wakuraya has more goats than Muchoki and if Muchoki gives Wakuraya one of his goats, Wakuraya will have twice as many goats as Muchoki. If Wakuraya gives Muchoki one of his goat, they will have an equal number of goats. How many goats does each have.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Simiyu has six times as many one-shilling coins as twenty-shillings coins, a third as many five-shillings coins as one-shilling coins and four times as many ten-shillings coins as twenty-shilling coins. If in total he has Ksh. 228, find the number of coins he has. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The figure below shows the angles of a polygon ABCDE.</p>
<p><img src="figures/fig1.png" class="img-fluid"></p>
<p>Obtain the size of each of the following angles,</p>
<p>a) CBA <span class="math inline">\((2mks)\)</span></p>
<p>b) CDE <span class="math inline">\((1mk)\)</span></p></li>
<li><p>The figure below is a cross-section of a swimming pool.</p>
<p><img src="figures/fig2.png" class="img-fluid"></p>
<ol type="a">
<li><p>Find the capacity of the pool in litres given that its length is 27m. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Given that the water has a density of <span class="math inline">\(1g/cm^3\)</span>, calculate the mass of water in the pool <span class="math inline">\((2mks)\)</span></p></li>
</ol></li>
<li><p>Food aid 492,850 French Franc was donated to the Turkana drought stricken area. The food was purchased from United States of America (USA) and paid for in US dollars. Calculate the exact value of the food aid in dollars if: <span class="math inline">\((3mks)\)</span></p>
<p><span class="math inline">\(1\, French \, Franc = ksh \,12.80\,\)</span> and <span class="math inline">\(\,1 \,Us \,dollars = ksh \,102.50\)</span></p></li>
<li><p>Munene is paid commission at the rate of 5 cents in every shilling on all goods he sells. During one month he sold 15 computers at Ksh. 14,200 each, 6 DVD players at Ksh. 6,800 each and 8 laptops at Ksh. 31,500 each. Calculate the total commission he earned in that month. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Sarah bought 3 plates and 6 jugs at a total cost of Ksh. 324. If she had bought 1 plate more and 2 jug less, she would have spent Ksh. 48 less. On another occasion Sarah bought 5 plates and 5 jugs at the same prices. Find how much she spent on the second occasion. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A boat Q is 300m due west of boat P. Another boat R is 240m on a bearing of <span class="math inline">\(155^0\)</span> from boat Q. Using scale drawing, find the distance ad bearing of boat R from P. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Two coils which are made by winding copper wire of different gauges and length have the same mass. The first coil is made by winding 250 metres of wire with cross sectional diameter 2.1mm while the second coil is made by winding a certain length of wire with cross-sectional diameter 1.4mm. Find the length of wire in the second coil. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>To prepare hay for the daily animals, green grass is dried and then processed into bails. In the process the mass of green grass decreases in the ratio 5:17. Determine the mass of green grass which must be processed to produce 1.2 tonnes of dry hay.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Evaluate using squares and square root tables. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\left[\sqrt[]{27.47}+(0.701)^2 \right]^2\]</span></p>
<ol start="14" type="1">
<li>Simplify: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{(4a+b)^2-(b-4a)^2}{(a+b)^2-(b-a)^2}\]</span></p>
<ol start="15" type="1">
<li><p>The radius of a cylindrical tin is increased by <span class="math inline">\(24\%\)</span> while its height is reduced by <span class="math inline">\(18\%\)</span>. In 4 significant figures find the percentage increase in the volume of the milk in the tin.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Taps A and B can fill a water tank in 40 minutes and 30 minutes respectively while C can empty in 20 minutes. If the three taps are turned on for 15 minutes then B and C closed. How long would it take before the tank is filled? <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>A rectangular aluminum sheet whose density is <span class="math inline">\(2.2 g/cm^3\)</span> is 1.2 m long, 80 cm wide, and 1.5 mm thick. A square of side 10 cm is cut off from each of the four corners of the rectangle and the remaining part folded into an open cuboid.</p>
<p>a) Calculate:</p>
<p>i) To the mass of the empty cuboid to the nearest Kg. <span class="math inline">\((4mks)\)</span></p>
<p>ii) The capacity of the cuboid in litres <span class="math inline">\((2mks)\)</span></p>
<p>b) If the cuboid is filled with alcohol whose density is <span class="math inline">\(0.75 g/cm^3\)</span>, calculate the mass of the cuboid when full of alcohol. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>A bus left Dodoma on Thursday evening and traveled to Mombasa according to the travel table below and arrived there on Saturday morning.</p>
<p><img src="figures/Md3_Q18.png" class="img-fluid"></p>
<ol type="a">
<li><p>Calculate the total:</p></li>
<li><p>Travelling time for the whole journey. <span class="math inline">\((3mks)\)</span></p>
<p>i. Stoppage time in all stations <span class="math inline">\((3mks)\)</span></p>
<p>ii. Time taken for the whole journey <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Given that the average speed of the bus for the whole journey is 60km/h, calculate the distance between Dodoma and Mombasa. <span class="math inline">\((2mks)\)</span></p></li>
</ol></li>
<li><p>Three cargo ships P, Q, and R are at sea such that ship Q is 300 km on a compass bearing of <span class="math inline">\(N35^0W\)</span> from ship P. ship R is 420 km on a bearing of <span class="math inline">\(220^0\)</span> from ship Q. Another ship S is reported to be 475 km from ship R and due south of ship P.</p>
<p>a) Draw an accurate scale drawing showing the positions of ships P, Q, R, and S. (use scale 1cm=50 km) <span class="math inline">\((5mks)\)</span></p>
<p>b) Use your scale drawing to determine the:</p>
<p>i) Distance of ship S from P. <span class="math inline">\((1mk)\)</span></p>
<p>ii) Distance and bearing of ship S from ship Q <span class="math inline">\((2mks)\)</span></p>
<p>iii) Compass bearing of ship S from ship R <span class="math inline">\((2mks)\)</span></p></li>
<li><p>(a) A solution whose volume is 50 litres is made up of <span class="math inline">\(40\%\)</span> water and <span class="math inline">\(60\%\)</span> alcohol. When n litres of water are added the percentage of alcohol drops to <span class="math inline">\(50\%\)</span>. Find the value of n.&nbsp;<span class="math inline">\((4mks)\)</span></p>
<p>(b) 15 litres of water is added to the new solution. Calculate the percentage of alcohol in the resulting solution. <span class="math inline">\((2mks)\)</span></p>
<p>(c) If 6 litres of the solution in (b) above is added to 3 litres of the original solution, calculate in the simplest form, the ratio of water to alcohol in the resulting solution. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Gabriel, an artisan made an article and sold it to a wholesaler to a profit of <span class="math inline">\(25\%\)</span>. The wholesaler sold it to a retailer at a profit of <span class="math inline">\(32\%\)</span>. The retailer finally sold the article to a customer at a profit of <span class="math inline">\(45\%\)</span>.</p>
<p>a) If Gabriel used sh 1200 to make the article, find how much the customer paid for it. <span class="math inline">\((3mks)\)</span></p>
<p>b) A customer paid sh 4785 for another article. Calculate how much the wholesaler had paid for it. <span class="math inline">\((3mks)\)</span></p>
<p>c) During a clearance sale the retailer reduced his prices by <span class="math inline">\(20\%\)</span>. Find the percentage profit the retailer made on an article which had cost Gabriel sh 4000 to make it.<span class="math inline">\((4mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate without using a calculator or Mathematical tables leaving your answer in the simplest form. <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[ \frac{\frac{3}{9}\,of\,\left(\frac{2}{5}-\frac{1}{10}\right)}{\left(4+\frac{2}{3}\right)\div\left(1+\frac{4}{3}\right)}\]</span></p>
<ol start="2" type="1">
<li><p>Three similar 21 inch television sets and five similar 17 inch television cost Ksh. 145,000. The difference between the cost of two 21 inch television sets and three 17 inch television Sets is Ksh. 8,000. Calculate the price of a 21- inch television set and that of 17-inch Television set. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Kenya bank buys and sells foreign currencies as shown.</p></li>
</ol>
<pre><code>                               Buying (Ksh)                   Selling (Ksh)
    1 Euro                      115.15                          115.26
    100 Japanese Yen             90.37                           90.45
    </code></pre>
<p>A Japanese traveling from France to Kenya had 4500 Euros. He converted all the 4500 Euros to Kenya shilling at the bank. While in Kenya, he spent a total of Ksh.225,600 and then converted the remaining Kenya shilling to Japanese Yens at the bank. Calculate the amount in Japanese Yen that he received. <span class="math inline">\((3mks)\)</span></p>
<ol start="4" type="1">
<li>Use tables of square and square roots to evaluate.<span class="math inline">\((4mks)\)</span></li>
</ol>
<p><span class="math display">\[(0.3264)^2+\sqrt[]{364.5}\]</span></p>
<ol start="5" type="1">
<li><p>A business woman usually makes a profit of <span class="math inline">\(32\%\)</span> by selling a pair of shoes at sh 1650. If she reduces the price of the shoes by sh 250, calculate the percentage profit she will now make. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Kinyua bought soya and millet at Ksh.75 per kg and Ksh.45 per kg respectively. He then mixed them and sold the mixture at Ksh.65 per kg making a profit of <span class="math inline">\(30\%\)</span>. Determine the ratio of soya to millet in mixture. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The curved surface area of a cylindrical container is <span class="math inline">\(2540cm^2\)</span>. If the radius of the container is 28cm, calculate to one decimal place the capacity of the container in litres <span class="math inline">\((Take \pi=\frac{22}{7} )\)</span>. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>The radius of a cylindrical tin is decreased by <span class="math inline">\(20\%\)</span> while its height is increased by <span class="math inline">\(12\%\)</span>. In 4 significant figures find the percentage change in the volume of the milk in the tin and indicate whether it is an increase or a decrease. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Wang’ombe, a farmer, uses <span class="math inline">\(\frac{1}{2}\)</span> of his land to plant cassava, <span class="math inline">\(\frac{1}{5}\)</span> for planting sweet potatoes, <span class="math inline">\(\frac{1}{3}\)</span> of the remainder for grazing and the rest for maize plantation. If he uses 10 hectares for grazing, determine how much land he uses for maize plantation. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Pauline bought 7 kg of rice and 3 KDF cakes at a total cost of Ksh. 450. Wathitha bought 5 kg of rice and 8 KDF cakes at the same prices and spent Ksh. 70 less than Pauline. Calculate the cost of each item. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>(a) Using a pair of compasses and a ruler only construct a triangle ABC such that <span class="math inline">\(AB = 6cm,\)</span> <span class="math inline">\(BC = 8cm\)</span> and <span class="math inline">\(ABC = 135^0\)</span>. <span class="math inline">\((2mks)\)</span></p>
<p>(b) Construct the height of triangle ABC in (a) above taking BC as the base and measure the height. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>One interior angle of a polygon is equal to <span class="math inline">\(40^0\)</span> and each of the other interior angles are <span class="math inline">\(125^0\)</span>.Find the number of sides of the polygon. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Given that <span class="math inline">\(x=2\)</span>, <span class="math inline">\(y=-1\)</span>, and <span class="math inline">\(z=3\)</span>, find the value of; <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[ \frac{5x^2-4y^2z+6y}{4x^2z+5y^3-z^3}\]</span></p>
<ol start="14" type="1">
<li><p>Three boats X, Y, and Z are situated in such a way that boat Y is 450 m on a compass bearing of <span class="math inline">\(S55^0E\)</span> from boat X. Boat Z is 600 m on a bearing of <span class="math inline">\(035^0\)</span> from boat Y.</p>
<p>a) Draw a sketch showing the positions of X, Y, and Z. <span class="math inline">\((1mk)\)</span></p>
<p>b) Calculate the distance of boat Z from boat X. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Pipe P can fill a tank in 6 minutes while pipe Q can fill the same tank in 10 minutes. On the other hand, a drainage pipe R, can empty the same full tank in 5 minutes. If Pipes P and Q are opened and left running for 3 minutes and then the drainage pipe R is then opened and all three left running, determine how many more minutes it takes to fill the drum. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="16" type="1">
<li><p>Mucagara secondary school hired a number of buses and matatus to ferry the students for an academic trip to Mombasa. The number of buses hired were two-third as many as matatus and no vehicle made a double trip. Each Matatu can carry a maximum of 18 students and a bus can carry three times as many students. The hire charges were Ksh. 8,400 per bus and Ksh. 4,800 per matatu. A total of Ksh. 62,400 was spent on transport for the trip.</p>
<p>a) Calculate the number:</p>
<p>i) Of buses hired <span class="math inline">\((4mks)\)</span></p>
<p>ii) Of matatus hired <span class="math inline">\((1mk)\)</span></p>
<p>b) Calculate the number of students who took the trip if each vehicle was filled to capacity.<span class="math inline">\((3mks)\)</span></p>
<p>c) Each student contributed Ksh 150 towards the cost of the trip and the school paid the remaining amount. Calculate the amount the school paid. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Three business dealers Kavula, Nzuki, and Ngina decided to buy a bus. They agreed to pay for the bus in the ratio 6:7:5. Using the marked price of the bus, Kavula was supposed to contribute Ksh. 120,600 more than Ngina. However, the sales agent allowed them a <span class="math inline">\(10\%\)</span> discount after paying it on cash.</p>
<p>a) Determine:</p>
<p>i) The marked price of the bus. <span class="math inline">\((3mks)\)</span></p>
<p>ii) The price at which they bought the bus. <span class="math inline">\((2mks)\)</span></p>
<p>iii) How much more Kavula and Ngina paid than Nzuki? <span class="math inline">\((2mks)\)</span></p>
<p>c) The dealers agreed that they would share monthly profits from the bus in the ratio of their contribution after setting aside <span class="math inline">\(10\%\)</span> of the profits. If in one month the bus realized Ksh. 120,900 as the profit, how much did Ngina got? <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A train left Nairobi on Monday evening and traveled to Mombasa according to the travel time table below. The train arrived in Lamu on Wednesday morning of the same week.</p>
<p><img src="figures/Md4_Q18.png" class="img-fluid"></p>
<p>a) Calculate the time the train took to travel between: <span class="math inline">\((4mks)\)</span></p>
<p>i) Nairobi and Mtito Andei</p>
<p>ii) Mtito Andei and Voi</p>
<p>iii) Voi and Mombasa</p>
<p>iv) Mombasa and Lamu</p>
<p>b) Determine the total time for the whole journey. <span class="math inline">\((4mks)\)</span></p>
<p>c) Given that the railway road distance between Nairobi and Lamu is 1505 Km, calculate the average speed for the whole journey. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>The following measurements were recorded in a field book using XY as the base line. <span class="math inline">\(XY = 400m\)</span>.</p>
<p><img src="figures/Md4_Q19.png" class="img-fluid"></p>
<p>a) Using a scale of 1: 4000, draw an accurate map of the farm. <span class="math inline">\((4mks)\)</span></p>
<p>b) Determine the actual area of the farm in hectares. <span class="math inline">\((4mks)\)</span></p>
<p>c) If the farm is on sale at Ksh. 100,000 per hectare, find how much the farm costs. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Karani bought some eggs at Ksh 96 per dozen and sold three-quarter of them at Ksh 280 per tray and the remainder at Ksh 270 per tray. In so doing she made a profit of Ksh 675. Given that one tray holds 30 eggs, calculate:</p>
<p>a) The number of eggs she bought. <span class="math inline">\((4mks)\)</span></p>
<p>b) The percentage profit she made giving your answer to three significant figures. <span class="math inline">\((3mks)\)</span></p>
<p>c) The percentage profit she would have made if she sold all the eggs at sh 280 per tray. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate. <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{\left(32-(-16)\right)}{-8}-\frac{\left(18-(-)(-6)\right)}{3}\]</span></p>
<ol start="2" type="1">
<li><p>The cost of 5 skirts and 3 blouses is Ksh. 1750. Afro’s wife bought three skirts and one of the blouses for Ksh. 850. Find the cost of each item. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Last year, Gaceru was four times as old as his son, Kairu; in four years’ time the sum of their ages will be 55. Determine their present ages. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Given that <span class="math inline">\(x=4\)</span>, <span class="math inline">\(y= -3\)</span>, and <span class="math inline">\(z= -1\)</span> evaluate. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\frac{3(x+z)^2-2(x-y)(y-z)}{3(x+z)-(y-z)}\]</span></p>
<ol start="5" type="1">
<li><p>A plastic test tube is made up of hemispherical bottom and a cylindrical stem, both of internal radius 0.7cm.</p>
<p>a) Calculate the capacity of the test tube, given that its height is 12cm. <span class="math inline">\((3mks)\)</span></p>
<p>b) Given that the test tube is filled with a liquid of density <span class="math inline">\(0.75 g/cm^3\)</span>, calculate the mass in g of the liquid in the test tube <span class="math inline">\((1mk)\)</span></p></li>
<li><p>A saleslady earns commission at the rate of 3.5 cents per shilling for all sales up to Ksh 350,000 and at the rate of 4.5 cents per shilling on any sales above that. During a certain month she sold 26 pieces of second hand computers at Ksh 14,500 per computer, 6 laptop batteries at Ksh. 4,500 each and 60 pieces of laptop chargers at Ksh 1,200 each. Calculate the total commission she earned in that month. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Water and milk are mixed such that the ratio of the volume of water to that of milk are 4:1. Taking the density of water as <span class="math inline">\(1g/cm^3\)</span> and that of milk as <span class="math inline">\(1.25g/cm^3\)</span>, find the mass in grams of 2.4 litres of the mixture. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>An arc of a circle of length 9.24cm subtends an angle of <span class="math inline">\(108^0\)</span> at the centre of the circle. Calculate the area of the sector bounded by this arc. Take <span class="math inline">\(\pi=\frac{22}{7}\)</span>. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>When maize seeds are dried up after harvest the mass decreases in the ratio 7:15. Find the mass of dried maize which is obtained after drying 1725 kg of green maize. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Bag X contains 672 sweets, bag Y 504 sweets and bag Z 360 sweets all of different types. The sweets are to be shared among a group of students in such a way each gets the same number of each type. Find the largest possible number of students.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>On a map with a scale of <span class="math inline">\(1:50000\)</span>, a banana plantation covers an area of <span class="math inline">\(100\,cm^2\)</span>. Find the area of the plantation in hectares. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The radius of a cylindrical tin is increased by <span class="math inline">\(30\%\)</span> while its height is decreased by <span class="math inline">\(25\%\)</span>. If the capacity of the old tin is <span class="math inline">\(400 cm^3\)</span>, find the capacity of the new tin. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three towns P, Q, and R are such that tow Q is 90 km on a bearing of <span class="math inline">\(147^0\)</span> from town P and town R is 120 km on a bearing of <span class="math inline">\(057^0\)</span> from town Q.</p>
<p>a) Draw a sketch showing the positions of the three towns. <span class="math inline">\((1mk)\)</span></p>
<p>b) Calculate the distance between town P and R. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Find the exact value of: <span class="math inline">\((4mks)\)</span></p>
<p><span class="math inline">\(1.\dot{3}\dot{2}-0.5\dot{3}\)</span></p></li>
<li><p>Simplify the following expression by reducing it to a single fraction <span class="math inline">\((3mks)\)</span></p>
<p><span class="math display">\[\frac{4a-5}{5}-\frac{2a-3}{3}=\frac{1-a}{6}\]</span></p></li>
<li><p>Starting from midnight the minute hand of a clock moved so that the clock is showing quarter to one.</p>
<p>a) Find the angle through which the minute hand has moved. <span class="math inline">\((1mk)\)</span></p>
<p>b) Determine the area of the sector described by the minute hand given that its length is 10.5 cm to 4 s.f. <span class="math inline">\((2mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>Using the linear equations below:</p>
<p>a) Complete the tables below and then write down the point in coordinate form (x,y) as shown. <span class="math inline">\((4mks)\)</span></p>
<p><span class="math inline">\(2x+y=6\)</span></p>
<p><img src="figures/Md5_Q17a.png" class="img-fluid"></p>
<p><span class="math inline">\(3x-4y=9\)</span></p>
<p><img src="figures/Md5_Q17b.png" class="img-fluid"></p>
<p>b) Use graphical method by plotting the two linear equations on the same grid to solve the simultaneous equations: <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<span class="math display">\[\begin{equation}
\begin{split}
2x+y&amp;=6\\
3x-4y&amp;=9
\end{split}
\end{equation}\]</span>
<ol start="3" type="a">
<li>The line <span class="math inline">\(2x+y=6\)</span> meets x-axis and the line y-axis at the points A and B respectively. From the graph state the co-ordinates of A and B. <span class="math inline">\((2mks)\)</span></li>
</ol>
<!-- -->
<ol start="18" type="1">
<li><p>A rectangular sheet measuring 80 cm by 50 cm and 2mm thick is made of copper whose density is <span class="math inline">\(2.5 g/cm^3\)</span>. A square of side 5 cm is removed from each corner of the rectangle and the remaining part folded to form an open cuboid.</p>
<p>a) Calculate:</p>
<p>i) The area of the copper which forms the cuboid.<span class="math inline">\((2mks)\)</span></p>
<p>ii) The mass of the empty cuboid in Kilograms. <span class="math inline">\((4mks)\)</span></p>
<p>b) If the cuboid is filled with water whose density is <span class="math inline">\(1 g/cm^3\)</span>, calculate the mass of the cuboid when full of water. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>At 1400hr, two ships A and B leave port P and sail out to sea. Ship A sails at a steady speed of 55km/h on a bearing of <span class="math inline">\(060^0\)</span> while ship B sails at a steady speed of 40km/h on a bearing of <span class="math inline">\(140^0\)</span>. At 1800hr both ships radio back to port giving their positions. At the same time a third ship C gives its position as 300km due east of P.</p>
<p>a) Using a ruler and a pair of compass only, construct a scale drawing showing the positions of P, A, B, and C at 1800hr. <span class="math inline">\((4mks)\)</span></p>
<p>b) Use your scale drawing to determine:</p>
<p>i) Distance and compass bearing of B from A <span class="math inline">\((4mks)\)</span></p>
<p>ii) Distance of C from A <span class="math inline">\((2mks)\)</span></p>
<p>iii) Distance Of B from C <span class="math inline">\((2mks)\)</span></p></li>
<li><p>In the year 2016 Muriithi had 40 more hens than cocks and half as many ducks as cocks. In the year 2017 his hens increased by <span class="math inline">\(60\%\)</span>, his ducks increased by <span class="math inline">\(40\%\)</span> and his cocks decreased by <span class="math inline">\(20\%\)</span>. At the end of 2017 all his birds were 1335. Determine the percentage increase in the number of his birds in the year 2017. <span class="math inline">\((10mks)\)</span></p></li>
<li><p>(a) Using a ruler and a pair of compasses only, construct triangle <span class="math inline">\(ABC\)</span> in which <span class="math inline">\(BC=6\)</span> cm, <span class="math inline">\(AB=8.8\)</span> cm and angle <span class="math inline">\(ABC=22.5^0\)</span>. <span class="math inline">\((4mks)\)</span></p>
<p>(b) Measure AC and angle ACB. <span class="math inline">\((2mks)\)</span></p>
<p>(c) Construct a circle that passes through A, B and C. <span class="math inline">\((3mks)\)</span></p>
<p>(d) What is the radius of this circle? <span class="math inline">\((1mk)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{8\times \frac{1}{3} \,of \,9\div 2-\frac{2}{3} \,of \,144 \div 12+2\times3}{\frac{3}{4} \,of\, 36 \div 3-4\div \frac{2}{5} of 10+3\times-2}\]</span></p>
<ol start="2" type="1">
<li><p>Nyamu bought 5 pairs of trousers and 3 pairs of socks for sh 2,540. If the cost of three pairs of trousers and 5 pairs of socks is sh 1780, calculate the cost of two pairs of trousers and 6 pairs of socks. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Simplify: <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[ \frac{(4a+b)^2-(b-4a)^2}{(a+b)^2-(b-a)^2}\]</span></p>
<ol start="4" type="1">
<li><p>Taps P and Q can fill a water tank in 25 minutes and 20 minutes respectively while R can empty in 15 minutes. If the three taps are turned on for 12 minutes then Q and R closed. How long would it take before the tank is filled? <span class="math inline">\((3 mks)\)</span></p></li>
<li><p>The G.C.D of three numbers is 42 and their L.C.M is 1764. If two of the numbers are 84 and 294, what is the other smallest number? <span class="math inline">\((3 mks)\)</span></p></li>
<li><p>Gatungo sold a pullover to a customer for Ksh. 1240 after allowing her a 20% discount on the marked price. Find the price at which the pullover was marked. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>After harvesting the green maize, the seed are dried, treated and then packed in 70 kg bags. The mass of undried maize decreases in the ratio 4:7. Calculate the mass of the undried maize that must be dried to produce 8 such bags when packed. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Hannah paid rent which was <span class="math inline">\(\frac{3}{10}\)</span> of her net salary. She used <span class="math inline">\(\frac{1}{2}\)</span> the remaining amount to make a down payment for a plot. She gave her mother Ksh. 3,200 and did shopping worth Ksh. 5,000 for herself. She saved the remainder which was Ksh. 12,800. How much was the down payment that she made. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>The interior angles of an hexagon are <span class="math inline">\((2x + 30)^0\)</span>, <span class="math inline">\((3x - 15)^0\)</span>, <span class="math inline">\((2x + 45)^0\)</span>, <span class="math inline">\(3x^0\)</span>, <span class="math inline">\((3x - 40)^0\)</span> and <span class="math inline">\(x^0\)</span>. Find the value of the smallest exterior angle. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Kenya company received y US Dollars. The money was converted into Kenya Shillings in a bank which buys and sells foreign currencies.</p></li>
</ol>
<pre><code>                       Buying (in Ksh)        Selling (in (Ksh)
    1 Sterling Pound    125.78                  126.64 
    1 Us Dollar         102.66                  102.86
  </code></pre>
<ol type="a">
<li><p>If the company received Ksh.12,452,658, calculate the amount, y received to the nearest US Dollar <span class="math inline">\((2mks)\)</span></p></li>
<li><p>The company exchanged the above Kenya shillings into Sterling pounds to buy a car in Britain. Calculate the cost of the car to the nearest Sterling pound. <span class="math inline">\((2mks)\)</span></p></li>
</ol>
<!-- -->
<ol start="11" type="1">
<li><p>item Juma, Ali and Hassan share the profit of their business in the ratio 2: 3: 5 respectively. If Juma receives ksh. 56, 000. How much profit did the hassan get. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three police posts are such that Q is on a bearing of <span class="math inline">\(220^0\)</span> and 14 km from P while R is on a bearing of <span class="math inline">\(145^0\)</span> and 10 km from P.</p>
<p>a) Using a suitable scale, draw a diagram to represent the above situation. <span class="math inline">\((2mks)\)</span></p>
<p>b) From the scale drawing determine:</p>
<p>i) The distance and bearing of Q from R <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Eighteen laborers takes 15 days to plough 6 acres of land. Find the number of laborers required to plough 8 acres in 12 days. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Starting from noon the minute hand of a clock moved so that the clock is showing 18 minutes to one.</p>
<p>a) Find the angle through which the minute hand has moved. <span class="math inline">\((1mk)\)</span></p>
<p>b) Given that the minute hand is 15 cm long, find the length of the arc it describes in that time. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Two coils of the same mass are made by winding brass wire of different gauges and length. If the first coil is made by winding 324 m of the wire with 3.36 mm cross-sectional diameter and the second coil is made by winding a certain length of the wire with a cross-sectional diameter of 2.52 mm, find the length of the second coil wire. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Juakali artisan reduced the base radius of a cone shaped container by 15% but, increased its height by 45%. Find the in three s.f percentage change in its volume and state whether if the volume increased or decreased.(volume of a cone<span class="math inline">\(=\frac{1}{3}\pi r^2h\)</span>) <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>From a reservoir, water flows through a cylindrical pipe of diameter 0.3m at a rate of 0.28m per second.</p>
<p>a) Determine the number of litres of water discharged from reservoir in one hour. <span class="math inline">\((4mks)\)</span></p>
<p>b) The water flows from the reservoir for 15 hours per day for 22 days per month and serves a population of 3,000 families. Determine the average consumption of water per family per month giving your answer to the nearest 1 litres. <span class="math inline">\((4mks)\)</span></p>
<p>c) The water is charged at the rate of Ksh. 10.50 per 100 litres. Calculate to the nearest Kenya shilling the average water in a family per month. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>At noon, three ships P, Q, and R start together from port A and sail out to sea. Ship P sails at a steady speed of 40 km/h on a bearing of <span class="math inline">\(055^0\)</span>. Ship Q sails steadily at a speed of 60km/h due east of A and ship R sails steadily at 50km/h on a bearing of <span class="math inline">\(152^0\)</span>. At 1530hr all three ships radio back to port giving their positions.</p>
<p>a) Draw a sketch diagram showing the position of ships P, Q, and R at 1500hr. <span class="math inline">\((1mk)\)</span></p>
<p>b) Use a ruler and a pair of compasses only to construct a scale drawing showing the positions of the ships P, Q, and R with respect to port A at 1500 hrs (1cm=25km). <span class="math inline">\((5mks)\)</span></p>
<p>c) By measurement use your scale drawing to determine:</p>
<p>i) The distance and bearing of ship P from ship Q. <span class="math inline">\((2mks)\)</span></p>
<p>ii) The distance of ship R from ship Q. <span class="math inline">\((1mk)\)</span></p>
<p>iii) The distance of ship P from ship R. <span class="math inline">\((1mk)\)</span></p></li>
<li><p>(a) A small field was surveyed and the measurements recorded in a surveyor’s field book as in the table below.</p>
<p><img src="figures/Md6_Q19a.png" class="img-fluid"></p>
<p>Using a scale of 1cm to 15 m make an accurate drawing of the map of the field. <span class="math inline">\((4mks)\)</span></p>
<p>(b)</p>
<p>i) Find the area of the field. <span class="math inline">\((3mks)\)</span></p>
<p>ii) Assuming that the baseline in (a) runs in a northern direction give the position of D relative to A using compass bearing and distance. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Four trucks A, B, C and D are used to transport 27,000 bags of maize to a depot. However, trucks A and B together take 24 days to transport the same number of bags while trucks C and D together take 15 days. Truck A carries <span class="math inline">\(1\frac{1}{4}\)</span> times the number of bags B carries and C carries <span class="math inline">\(1\frac{2}{5}\)</span> times as much as D.</p>
<p>a) Determine the number of bags of maize transported by each truck per day. <span class="math inline">\((5mks)\)</span></p>
<p>b) All the trucks A, B C and D work together for 5 days, after which truck C and D are withdrawn. A and B work together for another 5 days after which truck A breaks down. How long does truck B take to complete the rest of the remaining bags? <span class="math inline">\((5mks)\)</span></p></li>
<li><p>A solution whose volume is 160 litres is made up of <span class="math inline">\(40\%\)</span> water and the rest alcohol. When x litres of water is added the percentage of alcohol drops to <span class="math inline">\(30\%\)</span></p>
<p>a) Find the value of x <span class="math inline">\((4mks)\)</span></p>
<p>b) If 1 litres of alcohol are added to the new solution, calculate the percentage of water in the resulting solution. <span class="math inline">\((2mks)\)</span></p>
<p>c) A blend is made by mixing 25 litres of the solution in (b) above with 20 litres of the original solution. Calculate in the simplest form, the ratio of water to that of alcohol in the blend. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{1\frac{1}{4}\,of\,20+3\frac{3}{4}\div \frac{3}{8}-4\frac{1}{2}\times3\frac{1}{3}}{5\frac{4}{9}\times1\frac{2}{7}-4\div \frac{2}{3}+\frac{3}{4}\,of\,12}\]</span></p>
<ol start="2" type="1">
<li>Use squares and square root tables to evaluate. <span class="math inline">\((4mks)\)</span></li>
</ol>
<p><span class="math display">\[ (0.9233)^2+\sqrt[]{15.2453}-0.223\]</span></p>
<ol start="3" type="1">
<li><p>A UK tourist comes to Kenya with <span class="math inline">\(\pounds, 65, 000\)</span>. He pays <span class="math inline">\(25\%\)</span> commission at the airport and his expenses in Kenya amounted to Ksh. 890,000. How much money did he remain with in Ksh? (Take <span class="math inline">\(1\, UK \pounds = Ksh. 130.50\)</span>) <span class="math inline">\((3mks)\)</span></p></li>
<li><p>All prime numbers less than 10 are arranged in a descending order to form a number which forms a quotient of 1883 with a certain number. Calculate the number <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Solve the equation <span class="math inline">\((2mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\frac{1}{2y}=\frac{3}{4y+1}\]</span></p>
<ol start="6" type="1">
<li><p>Daniel deposited 48 different notes in the bank. He had eight times as many two-hundred shilling notes as one-thousand shilling notes and half as many one-hundred shilling notes as two-hundred shilling notes. The rest were fifty shilling notes. If he deposited a total of Ksh. 9,450, find the number of fifty shilling notes he deposited. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Esther bought maize and sorghum flour from a vendor. She then mixed them in the ratio 4:3. She bought the maize flour at ksh.50 per kg and the millet flour at ksh. 71 per kg. If she was to sell and make a profit of <span class="math inline">\(25\%\)</span>. What should be the selling price of 1kg of the mixture? Give you answer correct to the nearest 10 cent. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Teresia sold a dress at Ksh. 1,290 after allowing a discount of Ksh. 160. If she did not allow any discount to the customer, she would have made a profit of <span class="math inline">\(25\%\)</span>. Calculate the percentage profit she made. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Nyambura bought 4 sufurias and 6 cups for Ksh. 850 from a hawker. If she had bought 3 sufurias and 9 cups she would have saved Ksh. 55. Calculate the cost of one sufuria. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Omondi is now two-third as old as his sister and twice as old as his younger brother. In six years’ time Omondi’s age will be 26 years less than the sum of ages of his sister and brother. Determine Omondi’s present age. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Juakali artisan reduced the base radius of a cone shaped container by <span class="math inline">\(15\%\)</span> but, increased its height by <span class="math inline">\(45\%\)</span>. Find the in three s.f percentage change in its volume and state whether if the volume increased or decreased (volume of a cone <span class="math inline">\(=\frac{1}{3}\pi r^2h\)</span> <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The sum of the interior angles of an n-sided polygon is <span class="math inline">\(720^0\)</span>. Find the value of n and hence give the name of the polygon. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A rectangular water tank has a base measuring 4.5m by 2m. This tank has water to a height of 90cm. Water is then pumped into this tank continuously from 2030 hours to 2140 hours at the rate of 1.2 litres per second. Find the new depth of water in the tank after this period of time giving your result in metres. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Four strings measuring 15cm, 20cm, 25cm and 30cm are cut into pieces of equal length so that exact number of pieces is obtained from each string without wastage. Find the longest length of each string. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>The number of students at Lorna Waddington High School is 600. On a particular day <span class="math inline">\(\frac{1}{5}\)</span> of the boys and <span class="math inline">\(\frac{1}{4}\)</span> of the girls attended a sports meeting. If 468 students were left behind, find how many more boys than girls attended the meeting. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Using ruler and a pair of compasses only:</p>
<p>i) Construct triangle ABC in which BC = 7.5 cm and angle <span class="math inline">\(ABC = 105^0\)</span> and angle <span class="math inline">\(BAC = 30^0\)</span>. <span class="math inline">\((3mks)\)</span></p>
<p>ii) Drop a perpendicular from A to meet line BC at P. Determine the area of triangle ABC. <span class="math inline">\((2mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>A protestant church hired a number of buses and matatus to transport a group of youths to Embu for a youths rally. The number of matatus was four times the number of buses. The hire charges were Ksh. 5,200 per matatu and Ksh. 9,000 per bus. The total cost of hiring the vehicles was Ksh. 59,600. Each matatu can carry 14 youths while a bus can carry three times as many.</p>
<p>a) Calculate:</p>
<p>i) The number of buses hired <span class="math inline">\((4mks)\)</span></p>
<p>ii) The number of matatus hired <span class="math inline">\((1mk)\)</span></p>
<p>b) Calculate the number of youths ferried to Embu if each vehicle was filled to capacity and no vehicle made a double trip. <span class="math inline">\((3mks)\)</span></p>
<p>c) Each youth contributed Ksh. 200 towards the cost of the trip and the church paid the remaining amount. How much did the church pay? <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Three business partners Muhammed, Maimuna , and Hasan decided to start a business. Muhammed contributed Ksh. 25,000, Maimuna contributed Ksh. 35,000, and Hasan contributed Ksh. 45,000 as business capital exclusive of rental fee. They rented a business premises that needed to be paid Ksh. 15,000 which was to be shared equally among them. They agreed to put <span class="math inline">\(25\%\)</span> of the profit obtained annually back in to the business and share the rest in the ratio of their contributions. The business realized Ksh. 128,000 as gross profits.</p>
<p>a) Find the ratio in which they contributed business capital and rental fees. <span class="math inline">\((3mks)\)</span></p>
<p>b) Calculate:</p>
<p>i) The profits shared. <span class="math inline">\((2mks)\)</span></p>
<p>ii) Each partner’s share of the profits. <span class="math inline">\((3mks)\)</span></p>
<p>iii) The percentage of Hasan share to the sum of Maimuna and Muhammed share. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>In 2008, the number of students in Mucagara Secondary School was 240, a <span class="math inline">\(20\%\)</span> increase over the number of students in 2007. The number of students dropped by <span class="math inline">\(5\%\)</span> in 2009 but, increased by <span class="math inline">\(25\%\)</span> in the year 2010.</p>
<p>a) Determine the number of students:</p>
<p>i) In the year 2007 <span class="math inline">\((2mks)\)</span></p>
<p>ii) In the year 2009 <span class="math inline">\((2mks)\)</span></p>
<p>iii) In the year 2010 <span class="math inline">\((2mks)\)</span></p>
<p>b) Express as a percentage the increase in the number students in the year 2010 over the that in the year 2008 <span class="math inline">\((2mks)\)</span></p>
<p>c) What was the percentage increase in student population between 2007 and 2009. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Use the given linear equations to:</p>
<p>a) Complete the table below <span class="math inline">\((4mks)\)</span></p>
<p><span class="math inline">\(3x+y=9\)</span></p>
<p><img src="figures/Md7_Q20a.png" class="img-fluid"></p>
<p><span class="math inline">\(x-2y=-4\)</span></p>
<p><img src="figures/Md7_Q20b.png" class="img-fluid"></p>
<p>b) Using graph solve the simultaneous equations: <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<span class="math display">\[\begin{equation}
\begin{split}
x-2y&amp;= -4\\
3x+y&amp;=9
\end {split}
\end{equation}\]</span>
<ol start="3" type="a">
<li>If the line <span class="math inline">\(3x+y= 9\)</span> cuts the x-axis and y-axis at A and B respectively, state the coordinates of A and B. <span class="math inline">\((2mks)\)</span></li>
</ol>
<ol start="21" type="1">
<li><p>A Parrot flies from a tree X to another tree Y which is 70m on a bearing of <span class="math inline">\(035^0\)</span> from X. From Y the dove flies 100 m due west to another tree Z and finally flies due south to another tree W which is on a bearing of <span class="math inline">\(230^0\)</span> from X.</p>
<p>a) Using a ruler and a pair of compasses only construct an accurate scale drawing showing the positions of X, Y, Z, and W. (scale : 1 cm=10 cm) <span class="math inline">\((4mks)\)</span></p>
<p>b) By measurement from your scale drawing determine:</p>
<p>i) The distance and bearing of Z from X. <span class="math inline">\((2mks)\)</span></p>
<p>ii) The distance of W from Z <span class="math inline">\((1mk)\)</span></p>
<p>iii) The distance of W from X <span class="math inline">\((1mk)\)</span></p>
<p>c) The compass bearing of W from Y. <span class="math inline">\((2mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[ \frac{6\times\frac{1}{3}\,of\,12\div2-\frac{1}{3}\,of\,36\div6+3\times4}{\frac{1}{4}\,of\,24\div2-24\div\frac{3}{5}\,of\,10+5\times(-2)}\]</span></p>
<ol start="2" type="1">
<li><p>Factorize completely <span class="math inline">\((3mks)\)</span></p>
<p><span class="math display">\[(x+y)(4x-5y)-(x+y)^2\]</span></p></li>
<li><p>Murimi, a cattle keeping farmer, has twenty five times as many cows as goats, and three-fifth as many sheep as goats.</p>
<p>a) If there are g goats, write down a simplified expression in g for the total number of animals Murimi has. <span class="math inline">\((1mk)\)</span></p>
<p>b) Given that there are 75 sheep, calculate as a percentage the sum of goats and sheep to the number of cows Murimi had. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Four interior angles of a hexagon are <span class="math inline">\(120^0\)</span>, <span class="math inline">\(115^0\)</span>, <span class="math inline">\(135^0\)</span> and <span class="math inline">\(80^0\)</span>. The fifth interior angle is twice times the sixth. Find, in degrees the sixth interior angle. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Munyiti uses <span class="math inline">\(\frac{1}{3}\)</span> of his farm for planting mangoes, <span class="math inline">\(\frac{1}{4}\)</span> for planting macadamia and <span class="math inline">\(\frac{2}{5}\)</span> of the remainder for grazing and home stead. He still has 6 hectares of unused land. Find the size of land Munyiti used for planting mangoes.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Use tables and squares roots to evaluate to 4 significant figures. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\left(\sqrt[]{245.6}+(4.436)^2\right)^\frac{1}{2}\]</span></p>
<ol start="7" type="1">
<li><p>A speaker coil which is made by winding 750 m of copper wire of cross-sectional diameter of 1.89 mm has the same mass as another coil of copper wire with cross-sectional diameter of 2.1 mm. Find the length of the wire making the second coil. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three children shared some money. Rose got <span class="math inline">\(0.\dot{5}\)</span> of the money and Mutua <span class="math inline">\(0.\dot3\)</span> of the remainder. Loice received the rest which was Ksh. 400. How much did Mutua get? <span class="math inline">\((4mks)\)</span></p></li>
<li><p>The sum of the interior angles of an n-sided polygon is <span class="math inline">\(1080^0\)</span>. Find the value of n and hence calculate the size of each exterior angle. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three metal rods of lengths 243cm, 270cm and 198cm were cut into shorter pieces all of the same length to make window grills. Calculate the length of the longest piece that can be cut from each of the rods and hence the total number of pieces that can be obtained from the rods. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A blend of juice is made from pineapple and passion. The cost of two limes of pineapple is Ksh. 162 and three limes of passion is Ksh. 414. In what ratio should the juice be mixed such that by selling the mixture at Ksh. 140 per lime a profit of <span class="math inline">\(40\%\)</span> is realized? <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Awino bought a shirt for Ksh. 1400 and sold it to a customer at a profit of <span class="math inline">\(35\%\)</span>. What is the marked price of the shirt if selling the shirt she had allowed her customer a <span class="math inline">\(10\%\)</span> discount on the marked price? <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Sarah bought 3 plates and 6 jugs at a total cost of Ksh. 324. If she had bought 1 plate more and 2 jug less, she would have spent Ksh. 48 less. On another occasion Sarah bought 5 plates and 5 jugs at the same prices. Find how much she spent on the second occasion. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A Kenyan tourist left Berlin, Germany for Nairobi, Kenya through Geneva, Switzerland. While in Geneva, he bought a watch worth 110.6 Deutsche marks. Using the exchange rates below:</p></li>
</ol>
<pre><code>1 Swiss Franc = 1.58 Deutsche marks.

1 Swiss Franc = 100.98 Kenya shillings.</code></pre>
<ol start="15" type="1">
<li><p>Find the value of the watch in:</p>
<p>a) Swiss Francs <span class="math inline">\((2mks)\)</span></p>
<p>b) Kenya shillings <span class="math inline">\((1mk)\)</span></p></li>
<li><p>Using a ruler and a pair of compasses only construct triangle ABC such that <span class="math inline">\(AB= 5.8\,cm\)</span>, <span class="math inline">\(BC = 7\,cm\)</span> and angle <span class="math inline">\(CBA = 75^0\)</span>. Measure angle <span class="math inline">\(CAB\)</span>. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Two pipes A and B each running alone can fill a Jerican in 6 hours and 10 hours respectively. a drainage pipe C can empty the full Jerican in 15 hours. If pipe A and B are turned on and left running for <span class="math inline">\(1\frac{1}{2}\)</span> hours and then the drainage pipe C is opened and all three left running, find how much longer it takes to fill the Jerican. <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="18" type="1">
<li><p>Peter bought a second hand probox and later sold it through a sales agent who charges <span class="math inline">\(6.5\%\)</span> commission on the price of the probox. He received Ksh. 392,700 from the agent after the latter had deducted his commission. Peter incurred a loss of <span class="math inline">\(30\%\)</span> on the price at which he had bought the probox.</p>
<p>a) Determine the price at which the agent sold the probox. <span class="math inline">\((2mks)\)</span></p>
<p>b) Find the price at which Peter had bought the probox <span class="math inline">\((3mks)\)</span></p>
<p>c) If the amount Peter paid for the probox was <span class="math inline">\(25\%\)</span> less than the price of the new probox, calculate the price of the new probox. <span class="math inline">\((3mks)\)</span></p>
<p>d) Express as a percentage the amount Peter received for his probox to its price when new. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Nyakio and Anyango went to buy clothes for their business. Nyakio spent Ksh. 20,150 to buy a number of dresses and skirts from a wholesaler A at Ksh. 450 per dress and Ksh. 200 per skirt. Anyango bought the same number of dresses and skirts from wholesaler B where she paid <span class="math inline">\(20\%\)</span> less per dress and <span class="math inline">\(10\%\)</span> more per skirt. It was found that Anyango spent Ksh. 2,710 less than Nyakio.</p>
<p>a) Determine the number of dresses and skirts each cloth dealer bought.<span class="math inline">\((4mks)\)</span></p>
<p>b) Nyakio sold all her clothes at a profit of <span class="math inline">\(20\%\)</span> per dress and <span class="math inline">\(40\%\)</span> per skirt. How much profit did she make? <span class="math inline">\((3mks)\)</span></p>
<p>c) Anyango also sold all her clothes at a profit of <span class="math inline">\(20\%\)</span> per dress and <span class="math inline">\(40\%\)</span> per skirt. Calculate to three significant figures the percentage profit she made. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A metal sheet measuring <span class="math inline">\(1 \,m\)</span> long and <span class="math inline">\(80 \,cm\)</span> wind is <span class="math inline">\(2\,mm\)</span> thick and its density is <span class="math inline">\(2.5 g/cm^3\)</span>. A square of side <span class="math inline">\(x\, cm\)</span> is removed from each of the four corners and the remaining part folded to form an open cuboid.</p>
<p>a) Calculate the area of the remaining part in terms of <span class="math inline">\(x\)</span>. <span class="math inline">\((2mks)\)</span></p>
<p>b) Given that the area of the remaining part is <span class="math inline">\(0.76 \,m^2\)</span>, calculate the value of <span class="math inline">\(x\)</span> and hence state the internal dimensions of the cuboid.<span class="math inline">\((3mks)\)</span></p>
<p>c) Calculate the mass in kg of the empty cuboid to two significant figures.<span class="math inline">\((2mks)\)</span></p>
<p>d) If the cuboid is filled with a liquid of density <span class="math inline">\(d \,g/cm^3\)</span> and its mass when full of the liquid is 39.8 kg, calculate the value of <span class="math inline">\(d\)</span>.<span class="math inline">\((3mks)\)</span></p></li>
<li><p>Use a ruler and a pair of compasses only for all the constructions in this question.</p>
<p>a) Construct a triangle <span class="math inline">\(ABC\)</span> in which <span class="math inline">\(BC=7cm\)</span>, <span class="math inline">\(AC=9cm\)</span>, and angle <span class="math inline">\(ACB=135^0\)</span> <span class="math inline">\((3mks)\)</span></p>
<p>b) Measure AB and angle ABC <span class="math inline">\((2mks)\)</span></p>
<p>c) From A drop a perpendicular to meet BC produced at D. <span class="math inline">\((1mk)\)</span></p>
<p>d) Measure AD and hence calculate the area of triangle ABC. <span class="math inline">\((2mks)\)</span></p>
<p>e) Mark a point E on AD such that area of triangle BEC is 1.5 the area of triangle ABC. <span class="math inline">\((1mk)\)</span></p>
<p>f) Complete triangle BEC and measure EC. <span class="math inline">\((1mk)\)</span></p></li>
<li><p>Town B is 250 km from a bearing of <span class="math inline">\(050^0\)</span> from town A. Town C is 350 km from town B and on a compass bearing of <span class="math inline">\(S57^0E\)</span> from town B. A fourth town D is on a bearing of <span class="math inline">\(240^0\)</span> from town C and due south of town A.</p>
<p>a) Using a scale of <span class="math inline">\(1\,cm=50 \,km\)</span>, draw an accurate scale drawing showing the positions of towns A, B, C, and D. <span class="math inline">\((5mks)\)</span></p>
<p>b) By measurement from your scale drawing, determine:</p>
<p>i) The distance AC <span class="math inline">\((1mk)\)</span></p>
<p>ii) The distance AD <span class="math inline">\((1mk)\)</span></p>
<p>iii) The distance CD <span class="math inline">\((1mk)\)</span></p>
<p>iv) The bearing of B from C <span class="math inline">\((2mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Evaluate: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{\frac{3}{5}\,of\,30+5\frac{5}{6}\div\frac{7}{12}-2\frac{2}{3}\times 1\frac{1}{2}}{5\frac{5}{8}\times1\frac{7}{9}-1\frac{1}{4}\,of\,4\frac{4}{5}+2\frac{4}{5}\div\frac{7}{10}}\]</span></p>
<ol start="2" type="1">
<li><p>A law firm bought 60 files at a total cost of Ksh. 10,000. Some files cost Ksh. 150 each while others cost Ksh. 250 each. Find the number of files which were bought at Ksh. 150 each. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Mutheu is now 10 years older than her younger brother. Six years ago the She was three times as old as his brother. Find their present ages. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Wambui marked a skirt at Ksh. 400 and sold it to a customer at a discount of <span class="math inline">\(15\%\)</span>. Find the percentage profit She made if she had bought the skirt at Ksh. 280. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Use tables to evaluate:- <span class="math inline">\((4mks)\)</span></p></li>
</ol>
<p><span class="math display">\[(6.342+3.289)^2-\sqrt[]{(432.85-124.45)}\]</span></p>
<ol start="6" type="1">
<li><p>Osinya constructed a closed wooden box with external measurements 1.5 metres long, 1.4 metres wide and 0.6 metres high. The wood used in constructing the box was 10.0cm thick and has a density of <span class="math inline">\(0.75g/cm^3\)</span>. Determine the:</p>
<p>a) Volume in <span class="math inline">\(cm^3\)</span> of the wood used in constructing the box. <span class="math inline">\((3mks)\)</span></p>
<p>b) Mass of the box in kilograms correct to 1 decimal place. <span class="math inline">\((1mk)\)</span></p></li>
<li><p>Factorize completely <span class="math inline">\((3mks)\)</span></p>
<p><span class="math display">\[(x-3y)(4x+3y)-(x-3y)^2\]</span></p></li>
<li><p>16 workers working at the rate of 9 hours a day can complete a piece of work in 14 days. How many more workers working at the rate of 7 hours a day wound complete the same job in 12 days. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>In a form one class there are 5 more boys than girls. On a certain day one-quarter of the boys and one-fifth of the girls went for a football games. If 8 students from this class went for the football game, find the number of students in the class. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Kamau toured Switerland from Germany. In Switzerland he bought his wife a present worth 150 Deutsche marks. If</p>
<p>1 Swiss Franc = 1.65 Deutsche marks</p>
<p>1 Swiss Franc = 100.90 Kenya shillings</p>
<p>Find the value of the present in:</p>
<p>a) Swiss Francs correct to 2 decimal places. <span class="math inline">\((1mk)\)</span></p>
<p>b) Kenya shillings correct to the nearest Ksh <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Find the least number of biscuits that can be packed into carton boxes which contain either 10 or 15 or 21 or 24 with leaving 5 biscuits unpacked. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A polygon of n sides has half of the interior angles <span class="math inline">\(140^0\)</span> each and the rest <span class="math inline">\(160^0\)</span> each. Find the value of n.&nbsp;<span class="math inline">\((2mks)\)</span></p></li>
<li><p>A coffee dealer mixes two brands of coffee, P and Q to obtain 50kg of the mixture worth Ksh. 60. If brand P is valued at Ksh. 80 per kg and brand Q is valued at Ksh. 50 per kg. Calculate the ratio in its simplest form in which brands P and Q are mixed. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>In a 3 digit number, the hundreds digits is 3 more than the units digit and the tens digit is thrice the hundreds digit. If the sum of the digits is 12, find the three digits. Write the number. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three similar pieces of timber of length 150cm, 140cm and 180cm are cut into equal pieces. Find the largest possible area of a square which can be made from any of the three pieces. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Arrange the following fractions in descending order. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[ \frac{3}{5},\frac{8}{9},\frac{1}{3},\frac{4}{7},\frac{3}{4}\]</span></p>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>Melvin bought a second hand minibus at later sold it through a sales agent who charged <span class="math inline">\(8\%\)</span> commission on the price at which she sold the minibus. She received Ksh. 699,200 from the agent after she had deducted her commission. Melvin made a profit of <span class="math inline">\(15\%\)</span> on the price at which she had bought the vehicle.</p>
<p>a) Calculate the price at which the sales agent sold the minibus. <span class="math inline">\((2mks)\)</span></p>
<p>b) Find the amount Melvin paid for the minibus. <span class="math inline">\((3mks)\)</span></p>
<p>c) If the amount Melvin paid was 50% less than the price of the new minibus, calculate its price when new. <span class="math inline">\((3mks)\)</span></p>
<p>d) Express as a percentage the amount Melvin received for the minibus to its price when new. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Given linear equations <span class="math inline">\(2x+y=7\)</span> and <span class="math inline">\(5x-3y=12\)</span>:</p>
<p>a) Complete the following tables: <span class="math inline">\((4mks)\)</span></p>
<p><span class="math inline">\(2x+y=7\)</span></p>
<p><img src="figures/Md9_Q18a.png" class="img-fluid"></p>
<p><span class="math inline">\(5x-3y=12\)</span></p>
<p><img src="figures/Md9_Q18b.png" class="img-fluid"></p>
<p>b) Use graphical method to solve the simultaneous equations: <span class="math inline">\((4mks)\)</span></p>
<span class="math display">\[\begin{equation}
\begin {split}
2x+y&amp;=7\\
5x-3y-12&amp;=0
\end{split}
\end{equation}\]</span>
<p>c) If the line <span class="math inline">\(2x+y-7=0\)</span> cuts x-axis and y-axis at point A and B respectively, state the coordinates of A and B. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>(a) Solution whose volume is 100 litres is made up of <span class="math inline">\(30\%\)</span> water and <span class="math inline">\(70\%\)</span> milk. When y litres of water are added the percentage of milk drops to <span class="math inline">\(40\%\)</span>. Find the value of y. <span class="math inline">\((4mks)\)</span></p>
<p>(b) Twenty five litres of water is added to the new solution. Calculate the percentage of milk in the resulting solution. <span class="math inline">\((2mks)\)</span></p>
<p>(c) If 8 litres of the solution in (b) above is added to 16 litres of the original solution, calculate in the simplest form, the ratio of water to milk in the resulting solution. <span class="math inline">\((4mks)\)</span></p></li>
<li><p>Kiptanui’s farm produced 13,600 bags of wheat in 2015 which was a decrease of <span class="math inline">\(15\%\)</span> over the production in 2014. In 2016, the production was a <span class="math inline">\(25\%\)</span> increase of the previous year but, in 2017 Kiptanui farm produced 16,405 bags of wheat.</p>
<p>a) Calculate the number of bags of wheat Kiptanui’s farm produced:</p>
<p>i) In 2014 <span class="math inline">\((2mks)\)</span></p>
<p>ii) In 2016 <span class="math inline">\((2mks)\)</span></p>
<p>b) What was the percentage decrease in production in 2017 over that of the previous year? <span class="math inline">\((2mks)\)</span></p>
<p>c) Determine the percentage increase in production in 2017 over that in 2014. Give your answer in 3 significant figure <span class="math inline">\((2mks)\)</span></p>
<p>d) Calculate the percentage increase in production in 2016 over that in 2014. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>The external measurements of a closed wooden box are 1.0 m long, 70 cm wide, and 40 cm high. The wood used in making the box is 1.5 cm thick and has a density of <span class="math inline">\(0.8 g/cm^3\)</span>. Given that the box contains 25 packets of tools and each packet holds a dozen tools each weighing 108.5 g, calculate:</p>
<p>a) The volume of wood used in making the box. <span class="math inline">\((4mks)\)</span></p>
<p>b) The mass of the empty box in kilograms to four significant figures. <span class="math inline">\((3mks)\)</span></p>
<p>c) The total mass of the box in kilograms to 3 significant figures. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Sample Paper 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><u><strong>SECTION A: (50 MARKS)</strong></u></p>
<p><strong>Answer all the question in this section</strong></p>
<ol type="1">
<li>Without using a calculator, evaluate: <span class="math inline">\((3mks)\)</span></li>
</ol>
<p><span class="math display">\[\frac{3\frac{1}{5}+\frac{2}{7}\,of\,1\frac{3}{4}-\frac{7}{10}}{1\frac{3}{4}-1\frac{4}{5}\div3\frac{3}{5}+3\frac{3}{4}}\]</span></p>
<ol start="2" type="1">
<li><p>The sum of the ages of three friends Kiama, Murugi, and Naomi is 78 years. Murugi is two and a third as old as Naomi and seven years older than Kiama. Calculate their ages. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A shirt which is marked for ksh. 750 is sold to a customer for Ksh. 673.50. What percentage discount is the customer allowed? <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Starting from noon the minute hand of a clock moved so that the clock is showing 25 minutes to one.</p>
<p>a) Find the angle through which the minute hand has moved. <span class="math inline">\((1mk)\)</span></p>
<p>b) Given that the minute hand is 14 cm long, find the length of the arc it describes in that time. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>A cylindrical tank of diameter 2.8 m and height 2.0 m is three-quarter full of water. This water is transferred to an empty rectangular container measuring 1.4 m long and 80 cm wide. Calculate the height of the water in the container in centimeters. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Three towns P, Q, and R are situated such that town Q is 40 km on a bearing of <span class="math inline">\(060^0\)</span> from town P. Town R is 90 km on a bearing of <span class="math inline">\(150^0\)</span> from town Q.</p>
<p>a) Draw a sketch showing the positions of towns P, Q, and R. <span class="math inline">\((1mk)\)</span></p>
<p>b) Calculate:</p>
<p>i) The size of angle PQR <span class="math inline">\((1mk)\)</span></p>
<p>ii) The distance of R from P <span class="math inline">\((2mks)\)</span></p></li>
<li><p>A school bought 40 books at a total cost of Ksh 10,800. Some books cost Ksh 200 each while others cost Ksh 300 each. Find the number of books which were bought at Ksh 200 each. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Muthoni is now four times as old as his daughter. In sixteen years’ time she will be twice as old as her daughter. Find their present ages. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Ali sold goods which were marked at Ksh. 450, 000 allowing a discount of <span class="math inline">\(5\%\)</span> to the customer. If he received Ksh. 35,055 as a commission for this sale, calculate the percentage rate of commission he was paid. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Solve the following expression <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\frac{3y-4}{2}-\frac{1-2y}{3}=\frac{2y-1}{4}\]</span></p>
<ol start="11" type="1">
<li><p>(a) The angles of a triangle are <span class="math inline">\((2x-15)^0\)</span>, <span class="math inline">\((x+35)^0\)</span> and <span class="math inline">\((5x-40)^0\)</span>. Write down an equation in x with three terms only for the sum of the angles of the triangle. <span class="math inline">\((1mk)\)</span></p>
<p>(b) Solve the equation in (a) above and hence find the size of the largest angle. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Gladys house is 25 km from the office where she works. She uses her car to travel to and from her office every day for 5 days a week. Her car consumes petrol at the rate of 1 litre for every 12 km and petrol costs Ksh. 112.20 per litre. Allowing 4 weeks for holidays in a year, calculate the amount of money Gladys spends on petrol going to and from her office in one year. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>The radius of a water can in form of cylinder is increased by <span class="math inline">\(20\%\)</span> while its height decreased by <span class="math inline">\(15\%\)</span>. If the capacity of the old can is <span class="math inline">\(250 cm^3\)</span>, find the capacity of the new can. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>In a certain school there are 30 more boys than girls. One-quarter of the boys and two-thirds of the girls are boarders. If there are 255 boarders, find the number of students in that school. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>After work a hawker had four times as many ten-shilling coins as twenty-shilling coins, eight times as many five-shilling coins as twenty-shilling coins and thrice as many one-shilling coins as ten-shilling coins. After counting his money he found that he had a total of Ksh. 560. Calculate the number of coins he had. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>Given that <span class="math inline">\(x=4\)</span>, <span class="math inline">\(y= -3\)</span>, and <span class="math inline">\(z= -1\)</span> evaluate. <span class="math inline">\((3mks)\)</span></p></li>
</ol>
<p><span class="math display">\[\frac{3x^2yz^2-4xy^2z^2+5x^2y^2z^2}{4xy^2z+3x^2yz-x^2y^2z}\]</span></p>
<p><u><strong>SECTION B (50 MARKS)</strong></u></p>
<p><strong><em>Attempt all the questions</em></strong></p>
<ol start="17" type="1">
<li><p>Tum bought a number of T-shirts and a number of trousers at Ksh 100 and Ksh 250 respectively from a wholesaler in which he spend Ksh 9,500. Kerich bought the same number of T-shirts and trousers from another wholesaler where he paid <span class="math inline">\(25\%\)</span> more for a T-shirt and <span class="math inline">\(14\%\)</span> less for a trouser. Therefore, Kerich spent Ksh 550 less than Tum.</p>
<p>a) Determine the number of T-shirts and trousers each guy bought. <span class="math inline">\((4mks)\)</span></p>
<p>b) If Tum sold all his clothes at a profit of <span class="math inline">\(40\%\)</span> per T-shirt and <span class="math inline">\(20\%\)</span> per trouser, determine the profit he would make. <span class="math inline">\((3mks)\)</span></p>
<p>c) Similarly, if kerich sold all his clothes at a profit of <span class="math inline">\(20\%\)</span> per T-shirt and <span class="math inline">\(40\%\)</span> per trouser, calculate the percentage profit he would make on the sale of all his clothes. <span class="math inline">\((3mks)\)</span></p></li>
<li><p>A rectangular sheet is 90 cm long and 70 cm wide. The sheet is 1.8 mm thick and made of material whose density is <span class="math inline">\(2.5g/cm^3\)</span>. A square of side t cm is removed from each corner and the remaining part folded to form an open cuboid.</p>
<p>a) Given that the area of the remaining part is <span class="math inline">\(A \,cm^2\)</span>, write down an equation for <span class="math inline">\(A\)</span> in terms of <span class="math inline">\(t\)</span>. <span class="math inline">\((2mks)\)</span></p>
<p>b) Calculate to one decimal place the mass of the empty cuboid in kg given that <span class="math inline">\(t= 5cm\)</span>. <span class="math inline">\(3mks)\)</span></p>
<p>c) Find the dimensions of the cuboid and hence calculate its capacity in litres. <span class="math inline">\((3mks)\)</span></p>
<p>d) If the cuboid is filled with liquid whose density is <span class="math inline">\(d\, g/cm^3\)</span> and its mass found to be 19.6 kg, calculate the value of <span class="math inline">\(d\)</span>. <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Boat A is 160 m from the base of a vertical cliff. From A the angle of elevation of the top of the cliff is <span class="math inline">\(38^0\)</span>. From another boat B nearer to the base of the cliff, the angle of elevation of the top of the cliff is <span class="math inline">\(60^0\)</span>. The two boats are on the same straight line in front of the cliff.</p>
<p>a) Using a scale of <span class="math inline">\(1 cm=20 m\)</span>, draw an accurate scale drawing to represent the above information. <span class="math inline">\((4mks)\)</span></p>
<p>b) Use your scale drawing to determine:</p>
<p>i) The height of the cliff <span class="math inline">\((2mks)\)</span></p>
<p>ii) The distance between the two boats <span class="math inline">\((2mks)\)</span></p>
<p>iii) The distance of boat B from the base of the cliff <span class="math inline">\((2mks)\)</span></p></li>
<li><p>A truck left Uganda on Wednesday evening and travelled to Mombasa according to the travel time table below arriving there on Friday morning.</p>
<p><img src="figures/Md10_Q20.png" class="img-fluid"></p>
<p>a) Calculate:</p>
<p>b) The time taken by the truck to travel from: <span class="math inline">\((4mks)\)</span></p>
<p>i) Kampala to Busia</p>
<p>ii) Busia to Naivasha</p>
<p>iii) Naivasha to Nairobi</p>
<p>iv) Nairobi to Mombasa</p>
<p>c) The total travelleing time between Kampala and Mombasa. <span class="math inline">\((2mks)\)</span></p>
<p>d) The total stoppage time during the whole journey <span class="math inline">\((2mks)\)</span></p>
<p>e) The average speed for the whole journey given that the distance between Kampala and Mombasa is 1995 km <span class="math inline">\((2mks)\)</span></p></li>
<li><p>Wanja, Murimi, Kareb, and Elisha decided to buy a minibus. They acceded to pay for the cost of the minibus in the ratio <span class="math inline">\(9:7:4:5\)</span>. Basing their calculations on the marked price of the minibus, they found that Wanja would pay Ksh. 320,500, more than Kareb. The sales operator however allowed them a <span class="math inline">\(20\%\)</span> discount on cash payment.</p>
<p>a) Calculate:</p>
<p>i) The marked price of the minibus. <span class="math inline">\((2mks)\)</span></p>
<p>ii) How much more Murimi and Kareb paid than Wanja.<span class="math inline">\((5mks)\)</span></p>
<p>b) The four friends agreed to divide their profit obtained from the minibus in the ratio of their contributions after setting aside 15% of the profits for maintenance. If the minibus made Ksh. 96,500 as the profit during one month, how much did Elisha received that month? <span class="math inline">\((3mks)\)</span></p></li>
</ol>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Scale Drawing.html" class="pagination-link" aria-label="Chapter Eighteen: Scale Drawing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Chapter Eighteen: Scale Drawing</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Answers to Problems to Solve.html" class="pagination-link" aria-label="SECTION THREE">
        <span class="nav-page-text">SECTION THREE</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Enlightening Mathematics Revision Book Volume 1 (2e) was written by Martin Nyamu and Ken Gatungo.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/analystnyamu/EnlighteningMath/edit/main/Model Sample Papers.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/analystnyamu/EnlighteningMath/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>